// media/js/lang.js

const frToEn = {
    "Accueil": "Home",
    "À propos": "About",
    "Contact": "Contact",
    "Mes Projets": "My Projects",
    "Projets Réseaux": "Network Projects",
    "Projets Dev": "Dev Projects",
    "Mes Compétences": "My Skills",
    "Voir le projet": "View project",
    "En savoir plus": "Learn more",
    "Plan du site": "Sitemap",
    "Suivant": "Next",
    "Recommencer le quiz": "Restart quiz",
    "Voir les résultats": "View results",
    "Afficher les réponses": "Show answers",
    "Toutes les réponses": "All answers",
    "Classement du Jour": "Daily Leaderboard",
    "Rang": "Rank",
    "Score": "Score",
    "Pseudo": "Nickname",
    "Commencer le Quiz": "Start Quiz",
    "Entrez votre pseudo...": "Enter your nickname...",
    "Envoyer": "Send",
    "Votre Nom": "Your Name",
    "Votre Message": "Your Message",
    "Veuillez entrer un pseudo d'au moins 2 caractères": "Please enter a nickname of at least 2 characters",
    "Préférences enregistrées avec succès.": "Preferences saved successfully.",
    "Vous avez refusé. Certaines fonctionnalités pourraient ne pas être sauvegardées.": "You declined. Some features might not be saved.",
    "Oups, page introuvable...": "Oops, page not found...",
    "Avez-vous essayé de l'éteindre et de la rallumer ? 💡": "Have you tried turning it off and on again? 💡",
    "← Retour à l'accueil": "← Back to home",
    "thomas@portfolio:~$": "thomas@portfolio:~$",
    "Application Console": "Console app",
    "Contactez-moi dès maintenant via le formulaire pour discuter de votre projet !": "Contact me now via the form to discuss your project!",
    "PowerPoint": "PowerPoint",
    "Jeunesse": "Youth",
    "Cosette Ikwanga": "Cosette Ikwanga",
    "15 questions techniques tirées au hasard. Un classement remis à zéro chaque minuit.": "15 technical questions drawn at random. A ranking reset every midnight.",
    "Seniors II": "Seniors II",
    "Documentation complète sur Word, Excel, Outlook et PowerPoint incluant des guides détaillés, astuces et bonnes pratiques. Le fichier ZIP contient des exemples pratiques, des modèles réutilisables et des démonstrations étape par étape.": "Complete documentation on Word, Excel, Outlook and PowerPoint including detailed guides, tips and best practices. The ZIP file contains practical examples, reusable templates, and step-by-step demonstrations.",
    "Génération PDF": "PDF generation",
    "Montriond-Ouchy": "Montriond-Ouchy",
    "Seniors": "Seniors",
    "Janvier 2025": "January 2025",
    "Mosquitto": "Mosquito",
    "Voir →": "View →",
    "Ma machine principale quotidienne, optimisée pour le développement, la productivité et le gaming fluide. Équipée des dernières technologies AMD pour des performances optimales sans compromis.": "My daily primary machine, optimized for development, productivity and smooth gaming. Equipped with the latest AMD technologies for optimal performance without compromise.",
    "Mon Setup Actuel": "My Current Setup",
    "📥 Télécharger .exe": "📥 Download .exe",
    "Type de prestation": "Type of service",
    "Thomas Mayoraz • Portfolio - Autres Projets": "Thomas Mayoraz • Portfolio - Other Projects",
    "Remoting": "Remoting",
    "Carte Mère": "Motherboard",
    "Logique": "Logic",
    "et je suis fier d'être membre actif du club de ping-pong": "and I am proud to be an active member of the ping-pong club",
    "(non communiqué)": "(not communicated)",
    "Non défini": "Undefined",
    "Montage PC": "PC mounting",
    "HTML5": "HTML5",
    "Thomas Mayoraz • Portfolio personnel": "Thomas Mayoraz • Personal portfolio",
    "Client Montage PC": "PC Mount Client",
    "Office 365": "Office365",
    "Kingston 32GB DDR5 6000MT/s CL30": "Kingston 32GB DDR5 6000MT/s CL30",
    "Discutons de votre projet": "Let's discuss your project",
    "Windows 11": "Windows 11",
    "Scripting & Développement Web": "Scripting & Web Development",
    "Thierry Savoy": "Thierry Savoy",
    "079 894 93 43": "079 894 93 43",
    "078 676 70 99": "078 676 70 99",
    "Configuration PC sur mesure": "Custom PC configuration",
    "TM": "TM",
    "Autres Projets": "Other Projects",
    "IoT & Messagerie": "IoT & Messaging",
    "Juin 2026": "June 2026",
    "Cabinet Dentaire Tivoli": "Tivoli Dental Office",
    "Autre (précisez dans le message)": "Other (specify in message)",
    "Thomas Mayoraz • Portfolio professionnel": "Thomas Mayoraz • Professional portfolio",
    ", un projet scolaire qui me permet de mettre en pratique mes compétences en développement web, en particulier pour la création d'un site web statique utilisant uniquement les langages": ", a school project that allows me to practice my web development skills, in particular for the creation of a static website using only the languages",
    "Base de données": "Database",
    "TERMINÉ": "DONE",
    "078 885 94 12": "078 885 94 12",
    "Thomas Mayoraz • Portfolio - Sites Web": "Thomas Mayoraz • Portfolio - Websites",
    "-- Sélectionner --": "-- Select --",
    "Découvrez mes configurations PC personnalisées, assemblées avec soin pour différents usages : gaming, workstation et home server. Chaque build est optimisé pour son usage spécifique.": "Discover my personalized PC configurations, carefully assembled for different uses: gaming, workstation and home server. Each build is optimized for its specific use.",
    "500 - 1000 CHF": "500 - 1000 CHF",
    "90%": "90%",
    "Février 2026": "February 2026",
    "Outlook": "Outlook",
    "Type de demande :": "Type of request:",
    "Les entraînements pour adultes se déroulent les mardis de 19h00 à 22h00": "Adult training takes place on Tuesdays from 7:00 p.m. to 10:00 p.m.",
    "Envoyer le message": "Send message",
    "De la création de sites web au montage PC, en passant par le dépannage informatique, je suis à votre disposition pour concrétiser vos projets technologiques.": "From website creation to PC assembly, including computer troubleshooting, I am at your disposal to bring your technological projects to fruition.",
    "La salle se trouve au collège de la Croix-d'Ouchy": "The room is located at the Croix-d'Ouchy college",
    "Adultes": "Adults",
    "Mes créations digitales et expériences web": "My digital creations and web experiences",
    "Jouer →": "Play →",
    "La salle de sport est ouverte la semaine en dehors des vacances scolaires": "The gym is open during the week outside school holidays",
    "Je vous remercie sincèrement pour votre visite sur mon site ! J'espère que vous apprécierez votre expérience et que vous trouverez les informations utiles. N'hésitez pas à me contacter par mail avec le petit boutton se trouvant en bas de page.": "I sincerely thank you for your visit to my site! I hope you enjoy your experience and find the information useful. Do not hesitate to contact me by email using the little button at the bottom of the page.",
    "Prêt à collaborer ?": "Ready to collaborate?",
    "Gigabyte B650E AORUS Elite X AX ICE": "Gigabyte B650E AORUS Elite",
    "IoT": "IoT",
    "À Propos - Thomas Mayoraz | Services Informatiques Lausanne": "About - Thomas Mayoraz | IT Services Lausanne",
    "Avril 2025": "April 2025",
    "projet du module 293": "module 293 project",
    "Téléphone": "Telephone",
    "Moosmann, Christophe": "Moosmann, Christophe",
    "Le classement se réinitialise tous les jours à minuit.": "The leaderboard resets every day at midnight.",
    "Présentation": "Presentation",
    "Portfolio Personnel": "Personal Portfolio",
    "Mes Services Informatiques dans la région de Lausanne": "My IT Services in the Lausanne region",
    "\"Intervention rapide et très professionnelle. Thomas a réussi à récupérer toutes mes données sur mon disque dur endommagé et m'a conseillé un super système de sauvegarde.\"": "\"Quick and very professional intervention. Thomas managed to recover all my data on my damaged hard drive and recommended a great backup system.\"",
    "★★★★★": "★★★★★",
    "Testez vos connaissances avec un quiz ludique sur l'informatique — rapide, instructif et parfait pour tous les niveaux !": "Test your knowledge with a fun computer science quiz — quick, informative and perfect for all levels!",
    "Me Contacter": "Contact me",
    "AMD Ryzen 7 7700X": "AMD Ryzen 7 7700X",
    "Site web personnel": "Personal website",
    "Les équipes du club": "Club teams",
    "Script PowerShell avancé permettant la collecte de données système sur plusieurs machines via le remoting. Fonctionnalités incluant la génération de rapports, l'export en CSV et la détection d'anomalies. Documentation complète incluse.": "Advanced PowerShell script enabling collection of system data across multiple machines via remoting. Features including report generation, CSV export and anomaly detection. Full documentation included.",
    "Formation": "Training",
    "Sortez à l'arrêt Délices": "Get out at the Délices stop",
    "Rapports": "Reports",
    "Configuration sur mesure selon vos besoins : gaming, bureautique, workstation. Conseil et assemblage.": "Customized configuration according to your needs: gaming, office, workstation. Advice and assembly.",
    "Rapport complet sur la création et configuration de deux machines virtuelles (Windows 11 et Ubuntu) avec VirtualBox. Guide détaillé d'installation, configuration réseau, partage de fichiers et optimisation des performances.": "Complete report on the creation and configuration of two virtual machines (Windows 11 and Ubuntu) with VirtualBox. Detailed installation guide, network configuration, file sharing and performance optimization.",
    "Sur ce site vous trouverez tout ce qu'il faut pour connaître le club, son histoire, ses équipes et sa salle.": "On this site you will find everything you need to know the club, its history, its teams and its room.",
    "Nouveaux projets techniques en préparation...": "New technical projects in preparation...",
    "5ème ligue Hommes Groupe 5, Tours 3&4": "5th League Men Group 5, Rounds 3&4",
    "021 791 41 32": "021 791 41 32",
    "Jeu": "Game",
    "Formulaire de contact - CTT Montriond Ouchy": "Contact form - CTT Montriond Ouchy",
    "Mai 2025": "May 2025",
    "Spécialisé dans les": "Specialized in",
    "Si votre demande est très urgente, n'hésitez pas à m'appeler directement, ou à m'écrire par": "If your request is very urgent, do not hesitate to call me directly, or write to me by",
    "Décembre 2024": "December 2024",
    "Projet d'apprentissage": "Learning project",
    "📊 Télécharger la Présentation": "📊 Download the Presentation",
    "0 - 500 CHF": "0 - 500 CHF",
    "Prochain projet C# en développement...": "Next C# project in development...",
    "Mastermind": "Mastermind",
    "Word": "Word",
    "📄 Télécharger le Rapport": "📄 Download the Report",
    "4ème ligue Hommes Groupe 4, Tours 1&2": "4th League Men Group 4, Rounds 1&2",
    "Il semble que vous soyez perdu dans le cyberespace. La page que vous cherchez a peut-être été supprimée, renommée, ou n'a tout simplement jamais existé.": "It seems you are lost in cyberspace. The page you are looking for may have been deleted, renamed, or simply never existed.",
    "Quiz Tech : Testez Vos Connaissances Informatiques": "Tech Quiz: Test Your Computer Knowledge",
    "MQTT": "MQTT",
    "Découvrez mes projets développés en C#, des applications console aux interfaces graphiques. Chaque projet représente un défi technique relevé et une compétence acquise.": "Discover my projects developed in C#, from console applications to graphical interfaces. Each project represents a technical challenge met and a skill acquired.",
    "Guide Office 365": "Office 365 guide",
    "Prénom :": "First name:",
    "Implémentation complète du jeu Mastermind en C#. Le joueur doit deviner une combinaison secrète de couleurs en un nombre limité d'essais. L'application fournit des indices après chaque tentative et gère différents niveaux de difficulté.": "Complete implementation of the Mastermind game in C#. The player must guess a secret combination of colors in a limited number of tries. The app provides hints after each attempt and manages different difficulty levels.",
    "Perrin, Guy": "Perrin, Guy",
    "Details de l'équipe": "Team details",
    ". L'objectif principal de ce projet est de m'aider à mieux comprendre les bases du développement web tout en mettant en valeur ma créativité et mes compétences techniques dans la réalisation d'un site fonctionnel et esthétique.": ". The main objective of this project is to help me better understand the basics of web development while showcasing my creativity and technical skills in creating a functional and aesthetic site.",
    "Automatisation": "Automation",
    "Prénom": "First name",
    "Site web d'entreprise": "Business website",
    "Console App": "Console App",
    "Seniors III": "Seniors III",
    "Vous trouverez ci-dessous un taleau contenant les différentes équipes du club et un lien permmettant d'accèder aux détails et à leurs résultats récents.": "Below you will find a table containing the different teams of the club and a link allowing access to details and their recent results.",
    ", je propose des solutions sur mesure pour particuliers et entreprises.": ", I offer tailor-made solutions for individuals and businesses.",
    "Systèmes d'Exploitation & Sécurité": "Operating Systems & Security",
    "Gyula Király": "Gyula Király",
    "\"Intervention rapide pour un dépannage sur mon ordinateur de travail qui refusait de démarrer. Réparation efficace et super conseils.\"": "\"Quick intervention for a repair on my work computer which refused to start. Effective repair and great advice.\"",
    "CTT Montriond Ouchy": "CTT Montriond Ouchy",
    "95%": "95%",
    "Ligue Romandie Dames": "Romandie Ladies League",
    "Accès au club": "Access to the club",
    "Bienvenue sur le site web du CTT Montriond-Ouchy": "Welcome to the CTT Montriond-Ouchy website",
    "Lian-Li GALAHAD II 360 Trinity Perf.": "Lian-Li GALAHAD II 360 Trinity Perf.",
    "PowerShell": "PowerShell",
    "Thomas Mayoraz • Portfolio - Builds PC": "Thomas Mayoraz • Portfolio - Builds PC",
    "75%": "75%",
    "2ème ligue Jeunesse Groupe 1": "2nd Youth League Group 1",
    "Configurations personnalisées et optimisées": "Customized and optimized configurations",
    "Excel": "Excel",
    "services informatiques à Lausanne": "IT services in Lausanne",
    "5ème ligue Hommes Groupe 3, Tours 3&4": "5th League Men Group 3, Rounds 3&4",
    "Configuration personnelle": "Personal configuration",
    "Copyright - 2025": "Copyright - 2025",
    "UI/UX": "UI/UX",
    "📦 Télécharger le dossier ZIP": "📦 Download ZIP folder",
    "Mon parcours scolaire à l'ETML m'a permis d'acquérir des bases solides en programmation, administration réseau, gestion de bases de données et montage PC. Mais ce n'est qu'un début : je continue à apprendre chaque jour grâce à mes projets personnels, mes lectures techniques et mes collaborations.": "My school career at ETML allowed me to acquire a solid foundation in programming, network administration, database management and PC assembly. But this is just the beginning: I continue to learn every day through my personal projects, my technical readings and my collaborations.",
    "16 ans": "16 years old",
    "Ville :": "City :",
    "Octobre 2024": "October 2024",
    "📦 Télécharger le Script": "📦 Download the Script",
    "Carte Graphique": "Graphics Card",
    "Les Entraînements": "Training",
    "Assemblages personnalisés et configurations optimisées à Lausanne. Du choix des composants à la mise en service, explorez mes réalisations hardware.": "Custom assemblies and optimized configurations in Lausanne. From the choice of components to commissioning, explore my hardware creations.",
    "Mail": "Email",
    "Alimentation": "Food",
    "Découvrez mes projets de développement web, des sites vitrines aux applications interactives. Chaque création reflète ma passion pour le web moderne et l'expérience utilisateur.": "Discover my web development projects, from showcase sites to interactive applications. Each creation reflects my passion for the modern web and user experience.",
    "🛠️ Mes services en détail": "🛠️ My services in detail",
    "mayoraz-net.ch": "mayoraz-net.ch",
    "🔥 Mes différents projets": "🔥 My different projects",
    "Algorithmique": "Algorithmic",
    "Qui suis-je?": "Who am I?",
    "Projet MQTT sur VM": "MQTT project on VM",
    "Plateforme de gestion": "Management platform",
    "3ème ligue Seniors Groupe 2": "3rd Senior League Group 2",
    "Adresse e-mail :": "E-mail address :",
    "🖥️": "🖥️",
    "Chargement des questions...": "Loading questions...",
    "En parallèle, je poursuis mes études en informatique à l'": "At the same time, I am continuing my studies in computer science at",
    "Autre": "Other",
    "Maxime D.": "Maxime D.",
    "Accès": "Access",
    "4ème ligue Hommes Groupe 5, Tours 1&2": "4th League Men Group 5, Rounds 1&2",
    "Site web que j'ai développé pour mon club de ping-pong, le CTT Montriond Ouchy. Interface moderne et responsive présentant les actualités du club, les équipes, les résultats des matchs et les informations pratiques pour les membres et nouveaux joueurs.": "Website that I developed for my ping-pong club, CTT Montriond Ouchy. Modern and responsive interface presenting club news, teams, match results and practical information for members and new players.",
    "Guide VirtualBox": "VirtualBox Guide",
    "Virtualisation Win11 & Ubuntu": "Win11 & Ubuntu virtualization",
    "📄 Rapport Technique": "📄 Technical Report",
    "Thaler, Yohan": "Thaler, Yohan",
    "VirtualBox": "VirtualBox",
    "Hommes III": "Men III",
    "Turnstile": "Turnstile",
    "Réclamation": "Claim",
    "Thinh Vi Nguyen": "Thinh Vi Nguyen",
    "Parlons de votre projet": "Let's talk about your project",
    "Client Dépannage": "Customer Troubleshooting",
    "Hommes V": "Men V",
    "1 To NVMe SSD + 128 Go SSD": "1TB NVMe SSD + 128GB SSD",
    "E-mail": "Email",
    "6x Lian-Li UNI FAN SL-INF 120 ARGB": "6x Lian-Li UNI FAN SL-INF 120 ARGB",
    "Bonjour ! Je m'appelle": "Good morning ! My name is",
    "Ventilation": "Ventilation",
    "Dames": "Ladies",
    "Des trophées sont à gagner dans les différents tournois": "Trophies are to be won in the different tournaments",
    "Guide": "Guide",
    "Király, Gyula": "Király, Gyula",
    "Documentation": "Documentation",
    "2000 - 5000 CHF": "2000 - 5000 CHF",
    "Réseau": "Network",
    "⚡ Demande urgente ?": "⚡ Urgent request?",
    "Ligue": "League",
    "Contactez-moi dès maintenant pour discuter de votre projet informatique, que ce soit un site web, un montage PC ou une assistance technique.": "Contact me now to discuss your IT project, whether it is a website, PC assembly or technical assistance.",
    "Dépannage informatique": "Computer troubleshooting",
    "Fonction": "Function",
    ", une école technique réputée, où j'approfondis mes connaissances dans le domaine du développement et de la programmation. Ce site web a été conçu dans le cadre de mon": ", a renowned technical school, where I deepen my knowledge in the field of development and programming. This website was designed as part of my",
    "Hardware, Montage PC & Dépannage": "Hardware, PC Assembly & Troubleshooting",
    "Le Club de Tennis de Table de Montriond-Ouchy (CTT Montriond-Ouchy) a été fondé en 1969 et est situé à Lausanne, dans le quartier de la Croix d'Ouchy. Le club compte aujourd'hui plus de 60 membres actifs, âgés de 7 à 77 ans. IlÀ propose des entraînements pour les jeunes le mercredi de 17h30 à 19h, et pour les adultes le mardi de 19h à 22h. La salle est fermée pendant les vacances scolaires. Le club se distingue par son ambiance conviviale, offrant à la fois des séances d'entraînement, du jeu libre et des compétitions.": "The Montriond-Ouchy Table Tennis Club (CTT Montriond-Ouchy) was founded in 1969 and is located in Lausanne, in the Croix d'Ouchy district. The club now has more than 60 active members, aged 7 to 77. IlÀ offers training for young people on Wednesdays from 5:30 p.m. to 7 p.m., and for adults on Tuesdays from 7 p.m. to 10 p.m. The room is closed during school holidays. The club stands out for its friendly atmosphere, offering training sessions, free play and competitions.",
    "Allez ensuite en direction du collège de la croix d'Ouchy et vous serez arrivé sur place.": "Then go towards the Collège de la Croix d'Ouchy and you will have arrived there.",
    "WhatsApp": "WhatsApp",
    "ou": "Or",
    "Vous trouverez ci-dessous le chemin pour accèder au club depuis la gare de lausanne.": "Below you will find the path to access the club from Lausanne train station.",
    "Jeu de Puissance 4 classique développé en C# pour la console. Deux joueurs s'affrontent pour aligner 4 jetons de leur couleur horizontalement, verticalement ou en diagonale. Le jeu inclut une grille interactive, la détection des victoires et la gestion des tours.": "Classic Power 4 game developed in C# for the console. Two players compete to align 4 tokens of their color horizontally, vertically or diagonally. The game includes an interactive grid, win detection and turn management.",
    "+41 76 612 20 53": "+41 76 612 20 53",
    "Les entraînements jeunesse se déroulent le mercredi de 17h30 à 19h00": "Youth training takes place on Wednesdays from 5:30 p.m. to 7:00 p.m.",
    "Budget approximatif (CHF)": "Approximate budget (CHF)",
    "Retour au Portfolio": "Return to Portfolio",
    "À Propos du site": "About the site",
    "Julien P.": "Julien P.",
    "💡 Navigation": "💡 Navigation",
    "[email protected]": "[email protected]",
    "Processeur": "Processor",
    "Conseil technique": "Technical advice",
    "Stockage": "Storage",
    "Adresse :": "Address:",
    "Votre demande a bien été envoyée et je vous en remercie.": "Your request has been sent and I thank you.",
    "Pour revenir à cette page depuis un site, rendez-vous en pied de page d'accueil de chaque site et cliquez sur le bouton de retour au portfolio.": "To return to this page from a site, go to the footer of the home page of each site and click on the return to portfolio button.",
    "Message :": "Message:",
    "Nom": "Name",
    "CSS3": "CSS3",
    "ETML": "ETML",
    "au numéro suivant :": "to the following number:",
    "Projets Divers": "Miscellaneous Projects",
    "L'histoire du club": "The history of the club",
    "Découvrez mon parcours, mes compétences et ma passion pour l'informatique. Expert en services informatiques basé à Lausanne, spécialisé dans les solutions techniques.": "Discover my background, my skills and my passion for IT. Expert in IT services based in Lausanne, specializing in technical solutions.",
    "Trésorier": "Treasurer",
    "🚀 Besoin d'un service ou d'un devis informatique ?": "🚀 Need an IT service or quote?",
    "🛠️": "🛠️",
    "Sites Web": "Websites",
    "Prochain projet en cours...": "Next project in progress...",
    "Hommes II": "Men II",
    "Refroidissement": "Cooling",
    "Que ce soit pour un site web, un montage PC ou un dépannage informatique, je suis là pour vous accompagner. Remplissez le formulaire ci-dessous et je vous répondrai dans les plus brefs délais.": "Whether for a website, PC assembly or computer troubleshooting, I am here to support you. Fill out the form below and I will respond to you as soon as possible.",
    "078 216 87 62": "078 216 87 62",
    "6ème ligue Hommes Groupe 3, Tours 3&4": "6th League Men Group 3, Rounds 3&4",
    "📍 Lausanne, Vaud • Apprenti Informatique ETML": "📍 Lausanne, Vaud • ETML IT Apprentice",
    "Rendez-vous sur la page de contact pour vous inscrire à nos entraînements": "Visit the contact page to sign up for our training",
    "et": "and",
    "SMS": "SMS",
    "Projets C#": "C# projects",
    "Patrick Henri Losey": "Patrick Henri Losey",
    "Responsive": "Responsive",
    "Hyte Y60": "Hyte Y60",
    "Implémentation d'un système de messagerie MQTT entre plusieurs machines virtuelles. Rapport détaillant l'installation de Mosquitto MQTT, la configuration des brokers/clients, la sécurité et des cas d'utilisation pratiques avec exemples de code.": "Implementation of an MQTT messaging system between several virtual machines. Report detailing Mosquitto MQTT installation, broker/client configuration, security and practical use cases with code examples.",
    "☀️": "☀️",
    "AMD Radeon RX 6750 XT": "AMD Radeon RX 6750 XT",
    "Club de Tennis de table de": "Table Tennis Club",
    "Message détaillé": "Detailed message",
    "2ème ligue Hommes Groupe 2, Tours 1&2": "2nd League Men Group 2, Rounds 1&2",
    "Mes Builds PC": "My PC Builds",
    "Projets variés incluant des rapports techniques, des guides pratiques, des documentations et autres créations. Une collection de travaux diversifiés et de ressources utiles.": "Various projects including technical reports, practical guides, documentation and other creations. A collection of diverse works and useful resources.",
    "Conseil Technique": "Technical Advice",
    "EN": "EN",
    "Demande d'information": "Request for information",
    "Entraîneur des jeunes": "Youth coach",
    "Mon propre site web vitrine et portfolio professionnel. Conçu de A à Z pour présenter mes services informatiques, mes réalisations et faciliter la prise de contact grâce à un design moderne, réactif et optimisé.": "My own showcase website and professional portfolio. Designed from A to Z to present my IT services, my achievements and facilitate contact thanks to a modern, responsive and optimized design.",
    "Le club se trouve à Lausanne en Suisse": "The club is located in Lausanne, Switzerland.",
    "3ème ligue Seniors Groupe 3": "3rd Senior League Group 3",
    "Equipes": "Teams",
    "Enermax Revo. DF2 850W 80+ Gold": "Enermax Revo. DF2 850W 80+ Gold",
    "Numéro :": "Number :",
    "Puissance 4": "Power 4",
    "Merci pour votre message !": "Thank you for your message!",
    "Développement d'une solution logicielle complète pour un cabinet dentaire. Réalisation d'une plateforme de gestion des patients et création d'un modèle de facturation automatisé sur mesure pour optimiser l'administration du cabinet.": "Development of a complete software solution for a dental practice. Creation of a patient management platform and creation of a tailor-made automated billing model to optimize practice administration.",
    "À propos du site": "About the site",
    "Bonjour ! Je m'appelle Thomas Mayoraz, j'ai 17 ans et je suis actuellement en 2ème année d'apprentissage informaticien (voie Infra avec Maturité) à l'ETML à Lausanne. Passionné par l'informatique depuis tout petit, j'ai décidé de faire de cette passion un métier.": "Good morning ! My name is Thomas Mayoraz, I am 17 years old and I am currently in the 2nd year of an IT apprenticeship (Infra with Maturity track) at ETML in Lausanne. Passionate about IT since I was little, I decided to turn this passion into a career.",
    "Mon GitHub": "My GitHub",
    "Wolfgang Klose": "Wolfgang Klose",
    "1ère ligue Seniors Groupe 1": "1st Senior League Group 1",
    "Question 1/15": "Question 1/15",
    "Ikwanga, Cosette": "Ikwanga, Cosette",
    "Responsable jeunesse": "Youth manager",
    "Thierry Crelier": "Thierry Crelier",
    "Hommes": "Men",
    "3ème ligue Hommes Groupe 3, Tours 3&4": "3rd League Men Group 3, Rounds 3&4",
    "Développement web professionnel à Lausanne. Sites responsives, applications web modernes et solutions digitales sur mesure pour votre entreprise.": "Professional web development in Lausanne. Responsive sites, modern web applications and tailor-made digital solutions for your business.",
    "Thomas Mayoraz - Services Informatiques Lausanne | Développement Web & Montage PC": "Thomas Mayoraz - IT Services Lausanne | Web Development & PC Editing",
    "Inscription": "Registration",
    "👨‍💻": "👨‍💻",
    "Chemin à emprunter :": "Path to take:",
    "Email": "Email",
    "Virtualisation": "Virtualization",
    ", un club dynamique où je pratique ce sport passionnant avec des personnes incroyables. Depuis que j'ai commencé à jouer, le ping-pong est devenu une véritable passion pour moi, et faire partie de ce club m'apporte de nombreuses opportunités d'amélioration et de convivialité au sein d'une communauté soudée.": ", a dynamic club where I practice this exciting sport with incredible people. Since I started playing, ping pong has become a real passion for me, and being part of this club brings me many opportunities for improvement and conviviality within a close-knit community.",
    "contact@mayoraz-net.ch": "contact@mayoraz-net.ch",
    "Applications console et projets académiques développés en C#. Découvrez mes solutions aux défis de programmation et mes créations personnelles.": "Console applications and academic projects developed in C#. Discover my solutions to programming challenges and my personal creations.",
    "6ème ligue Hommes Groupe 3, Tours 1&2": "6th League Men Group 3, Rounds 1&2",
    "Sophie L.": "Sophie L.",
    "Thomas Mayoraz • Portfolio - Projets C#": "Thomas Mayoraz • Portfolio - C# Projects",
    "Découvrir →": "Discover →",
    "Hommes IV": "Men IV",
    "Ubuntu": "Ubuntu",
    "Script PowerShell de Collecte": "PowerShell Collection Script",
    "Mes développements et applications en C#": "My developments and applications in C#",
    "Contacts du club": "Club Contacts",
    "← Retour au Portfolio": "← Return to Portfolio",
    "Entraînements": "Workouts",
    "Boîtier": "Housing",
    "Résolution de problèmes informatiques, installation de logiciels, optimisation des performances.": "Solving computer problems, installing software, optimizing performance.",
    "Nom :": "Name:",
    "Vous pouvez également m'écrire directement par email :": "You can also write to me directly by email:",
    "Plus de 5000 CHF": "More than 5000 CHF",
    "Yves Rousseau": "Yves Rousseau",
    "CSS": "CSS",
    "Rue :": "Street:",
    "Téléphone :": "Telephone:",
    "ACTIF": "ACTIVE",
    "Présentation PowerPoint complète guidant pas à pas l'installation et la configuration de VirtualBox. Contenu visuel avec captures d'écran, astuces d'optimisation et bonnes pratiques. Parfait pour former des débutants à la virtualisation.": "Complete PowerPoint presentation guiding step-by-step installation and configuration of VirtualBox. Visual content with screenshots, optimization tips and best practices. Perfect for training beginners in virtualization.",
    "3ème ligue Hommes Groupe 3, Tours 1&2": "3rd League Men Group 3, Rounds 1&2",
    "Sélectionnez un service": "Select a service",
    "← Retourner au site principal": "← Return to main site",
    "JavaScript": "JavaScript",
    "Client Récupération de Données": "Customer Data Recovery",
    "À Propos de moi": "About me",
    "Apprenti informaticien passionné": "Passionate IT apprentice",
    "Dépannage": "Troubleshooting",
    "Collecte de données": "Data collection",
    "\"Travail très professionnel ! Thomas a monté mon PC gaming avec un câblage impeccable. Tout tourne à merveille, je recommande vivement.\"": "\"Very professional work! Thomas set up my gaming PC with impeccable cabling. Everything works perfectly, I highly recommend.\"",
    "Virtualisation, Scripts & Guides Techniques": "Virtualization, Scripts & Technical Guides",
    "Thomas Mayoraz": "Thomas Mayoraz",
    "Équipe": "Team",
    ", j'ai": ", I have",
    "Président": "President",
    "Avez-vous essayé de l'éteindre et de la rallumer ? 🔌": "Have you tried turning it off and on again? 🔌",
    "85%": "85%",
    "Depuis la gare de lausanne dirigez-vous vers le metro M2 direction Ouchy olympique.": "From Lausanne station, head towards the M2 metro towards Ouchy Olympic.",
    "1ère ligue Hommes Groupe 1, Tours 3&4": "1st League Men Group 1, Rounds 3&4",
    "Création de sites personnels, portfolios, sites vitrines pour entreprises. Design moderne et responsive.": "Creation of personal sites, portfolios, showcase sites for businesses. Modern and responsive design.",
    "C#": "C#",
    "Mémoire Vive": "RAM",
    "HTML": "HTML",
    "1000 - 2000 CHF": "1000 - 2000 CHF",
    "Ce que disent mes clients": "What my customers say",
    "Date de naissance :": "Date of birth:",
    "la ville du club": "the club city",
    "À propos de moi": "About me",
    "Chloé Werner": "Chloe Werner",
    "Projet de Virtualisation": "Virtualization Project",
    "Administration Réseau & Serveurs": "Network & Server Administration",
    "Accompagnement dans vos choix technologiques, recommandations matériel et logiciel.": "Support in your technological choices, hardware and software recommendations.",
    "Prêt pour le défi ?": "Ready for the challenge?",
    "Je vous répondrai sous 24 heures.": "I will respond to you within 24 hours.",
    "la salle": "the room",
    "Services Informatiques Professionnels": "Professional IT Services",
    "Thomas Mayoraz • Services Informatiques Lausanne • Portfolio professionnel": "Thomas Mayoraz • IT Services Lausanne • Professional portfolio",
    "Quiz sur l'informatique": "Computer science quiz",
    "Capitaine": "Captain",
    "Découvrez mes projets techniques incluant des rapports de virtualisation, scripts PowerShell, implémentations MQTT et guides détaillés. Chaque projet est documenté avec soin et disponible en téléchargement.": "Discover my technical projects including virtualization reports, PowerShell scripts, MQTT implementations and detailed guides. Each project is carefully documented and available for download.",
    "Juin 2025": "June 2025",
    "\"À votre disposition pour tous vos besoins informatiques\"": "“At your disposal for all your IT needs”",
    "Chef technique": "Technical manager",
    "💬 Me Contacter Maintenant": "💬 Contact Me Now",
    "NPA :": "Postcode:",
    "les trophées": "the trophies",
    "🏆 Classement du Jour": "🏆 Ranking of the Day",
    "La jeunesse": "Youth"
,
    "Tutoriels": "Tutorials",
    "Homelab & Serveur": "Homelab & Server",
    "Admin Run": "Admin Run",
    "Base de Connaissances & Guides": "Knowledge Base & Guides",
    "Découvrez mes tutoriels, configurations et astuces d'administration système.": "Discover my tutorials, configurations, and system administration tips.",
    "Déploiement avec Docker Compose": "Deployment with Docker Compose",
    "Comment structurer vos conteneurs et réseaux avec Docker Compose pour une gestion simplifiée.": "How to structure your containers and networks with Docker Compose for simplified management.",
    "L'Auto-Healing avec n8n": "Auto-Healing with n8n",
    "Création de workflows n8n pour redémarrer automatiquement les services Docker qui plantent.": "Creating n8n workflows to automatically restart crashed Docker services.",
    "La Stack \"Arr\" (Jellyfin, Radarr...)": "The 'Arr' Stack (Jellyfin, Radarr...)",
    "Automatisation complète du téléchargement à la lecture en streaming avec le combo magique.": "Complete automation from downloading to streaming playback with the magic combo.",
    "Monitoring avec Prometheus & Grafana": "Monitoring with Prometheus & Grafana",
    "Mise en place de dashboards professionnels pour surveiller la santé de vos serveurs en temps réel.": "Setting up professional dashboards to monitor server health in real-time.",
    "VPN Sécurisé avec Tailscale": "Secure VPN with Tailscale",
    "Comment créer un réseau privé virtuel Mesh (WireGuard) sans ouvrir de ports sur votre box internet.": "How to create a Mesh Virtual Private Network (WireGuard) without opening ports on your router.",
    "Mon Infrastructure": "My Infrastructure",
    "Découvrez l'architecture technique de mon serveur personnel et les services auto-hébergés.": "Discover the technical architecture of my personal server and self-hosted services.",
    "Le Matériel": "Hardware",
    "Une machine virtuelle Ubuntu Server robuste, optimisée pour faire tourner des dizaines de conteneurs Docker sans transpirer.": "A robust Ubuntu Server virtual machine, optimized to run dozens of Docker containers without breaking a sweat.",
    "L'Usine à Médias": "Media Factory",
    "La stack 'Arr' (Radarr, Sonarr, Prowlarr) reliée à qBittorrent et exposée magnifiquement via Jellyfin pour le streaming.": "The 'Arr' stack (Radarr, Sonarr, Prowlarr) linked to qBittorrent and beautifully exposed via Jellyfin for streaming.",
    "Le Monitoring": "Monitoring",
    "Une surveillance constante grâce à Prometheus, qui remonte les métriques système vers des dashboards Grafana stylisés, sans oublier Netdata.": "Constant monitoring thanks to Prometheus, which sends system metrics to stylized Grafana dashboards, not forgetting Netdata.",
    "L'Auto-Réparation (n8n)": "Self-Healing (n8n)",
    "L'automatisation poussée à l'extrême : un workflow n8n qui surveille les conteneurs qui tombent en erreur et les relance de manière autonome.": "Automation pushed to the extreme: an n8n workflow that monitors containers failing and restarts them autonomously.",
    "Admin Run (T-Rex)": "Admin Run (T-Rex)",
    "Appuyez sur ESPACE pour faire sauter l'Administrateur Système au-dessus des bugs !": "Press SPACE to make the System Administrator jump over the bugs!",
    "Score :": "Score :",
    "Meilleur :": "Best :",
    "GAME OVER": "GAME OVER",
    "Appuyez sur Espace pour redémarrer": "Press Space to restart",
    "Statut des Services": "Service Status",
    "Network Status": "Network Status",
    "Systèmes 100% Opérationnels": "Systems 100% Operational",
    "Routeur Principal": "Main Router",
    "Pi-hole (DNS)": "Pi-hole (DNS)",
    "Reverse Proxy Nginx": "Nginx Reverse Proxy",
    "VPN Tailscale": "Tailscale VPN",
    "Cloudflare WAF": "Cloudflare WAF",
    "Serveur Ubuntu (VM)": "Ubuntu Server (VM)",
    "Moteur Docker": "Docker Engine",
    "Jellyfin Media Server": "Jellyfin Media Server",
    "Stack Arr (Sonarr, Radarr...)": "Arr Stack (Sonarr, Radarr...)",
    "Base de Données InfluxDB": "InfluxDB Database",
    "Grafana Dashboards": "Grafana Dashboards",
    "Prometheus Metrics": "Prometheus Metrics",
    "Netdata Live": "Netdata Live",
    "n8n Automation": "n8n Automation",
    "Opérationnel": "Operational",
    "🟢 System Status": "🟢 System Status",
    "Mon LinkedIn": "My LinkedIn"
};

const enToFr = {};
for (const [fr, en] of Object.entries(frToEn)) {
    enToFr[en] = fr;
}

let currentLang = localStorage.getItem('site_lang') || 'FR';

function translateTextNode(node, dict) {
    const text = node.nodeValue.trim();
    if (text && dict[text]) {
        node.nodeValue = node.nodeValue.replace(text, dict[text]);
    }
}

function applyLanguage(targetLang) {
    const isToEn = targetLang === 'EN';
    const activeDict = isToEn ? frToEn : enToFr;

    const walk = document.createTreeWalker(
        document.body,
        NodeFilter.SHOW_TEXT,
        null,
        false
    );

    let node;
    const nodesToTranslate = [];
    while ((node = walk.nextNode())) {
        if (node.parentElement && (node.parentElement.tagName === 'SCRIPT' || node.parentElement.tagName === 'STYLE')) {
            continue;
        }
        nodesToTranslate.push(node);
    }

    nodesToTranslate.forEach(n => translateTextNode(n, activeDict));

    const placeholders = document.querySelectorAll('input[placeholder], textarea[placeholder]');
    placeholders.forEach(inp => {
        const text = inp.getAttribute('placeholder');
        if (text && activeDict[text]) {
            inp.setAttribute('placeholder', activeDict[text]);
        }
    });

    const langBtn = document.getElementById('lang-toggle');
    if (langBtn) {
        langBtn.textContent = targetLang === 'EN' ? 'FR' : 'EN';
    }
    
    document.documentElement.lang = targetLang.toLowerCase();
}

document.addEventListener('DOMContentLoaded', () => {
    if (currentLang === 'EN') {
        applyLanguage('EN');
    }

    const langBtn = document.getElementById('lang-toggle');
    if (langBtn) {
        langBtn.addEventListener('click', () => {
            currentLang = currentLang === 'FR' ? 'EN' : 'FR';
            localStorage.setItem('site_lang', currentLang);
            applyLanguage(currentLang);
            
            if (typeof showToast === 'function') {
                showToast(currentLang === 'EN' ? 'Language switched to English 🌍' : 'Langue changée en Français 🌍', 'info');
            }
        });
    }
});
