// media/js/lang.js

const frToEn = {
    "Accueil": "Home",
    "À propos": "About",
    "Contact": "Contact",
    "Mes Projets": "My Projects",
    "Projets Réseaux": "Network Projects",
    "Projets Dev": "Dev Projects",
    "Mes Compétences": "My Skills",
    "Voir le projet": "View project",
    "En savoir plus": "Learn more",
    "Plan du site": "Sitemap",
    "Suivant": "Next",
    "Recommencer le quiz": "Restart quiz",
    "Voir les résultats": "View results",
    "Afficher les réponses": "Show answers",
    "Toutes les réponses": "All answers",
    "Classement du Jour": "Daily Leaderboard",
    "Rang": "Rank",
    "Score": "Score",
    "Pseudo": "Nickname",
    "Commencer le Quiz": "Start Quiz",
    "Entrez votre pseudo...": "Enter your nickname...",
    "Envoyer": "Send",
    "Votre Nom": "Your Name",
    "Votre Message": "Your Message",
    "Veuillez entrer un pseudo d'au moins 2 caractères": "Please enter a nickname of at least 2 characters",
    "Préférences enregistrées avec succès.": "Preferences saved successfully.",
    "Vous avez refusé. Certaines fonctionnalités pourraient ne pas être sauvegardées.": "You declined. Some features might not be saved.",
    "Oups, page introuvable...": "Oops, page not found...",
    "Avez-vous essayé de l'éteindre et de la rallumer ? 💡": "Have you tried turning it off and on again? 💡",
    "← Retour à l'accueil": "← Back to home",
    "thomas@portfolio:~$": "thomas@portfolio:~$",
    "Application Console": "Console app",
    "Contactez-moi dès maintenant via le formulaire pour discuter de votre projet !": "Contact me now via the form to discuss your project!",
    "PowerPoint": "PowerPoint",
    "Jeunesse": "Youth",
    "Cosette Ikwanga": "Cosette Ikwanga",
    "15 questions techniques tirées au hasard. Un classement remis à zéro chaque minuit.": "15 technical questions drawn at random. A ranking reset every midnight.",
    "Seniors II": "Seniors II",
    "Documentation complète sur Word, Excel, Outlook et PowerPoint incluant des guides détaillés, astuces et bonnes pratiques. Le fichier ZIP contient des exemples pratiques, des modèles réutilisables et des démonstrations étape par étape.": "Complete documentation on Word, Excel, Outlook and PowerPoint including detailed guides, tips and best practices. The ZIP file contains practical examples, reusable templates, and step-by-step demonstrations.",
    "Génération PDF": "PDF generation",
    "Montriond-Ouchy": "Montriond-Ouchy",
    "Seniors": "Seniors",
    "Janvier 2025": "January 2025",
    "Mosquitto": "Mosquito",
    "Voir →": "View →",
    "Ma machine principale quotidienne, optimisée pour le développement, la productivité et le gaming fluide. Équipée des dernières technologies AMD pour des performances optimales sans compromis.": "My daily primary machine, optimized for development, productivity and smooth gaming. Equipped with the latest AMD technologies for optimal performance without compromise.",
    "Mon Setup Actuel": "My Current Setup",
    "📥 Télécharger .exe": "📥 Download .exe",
    "Type de prestation": "Type of service",
    "Thomas Mayoraz • Portfolio - Autres Projets": "Thomas Mayoraz • Portfolio - Other Projects",
    "Remoting": "Remoting",
    "Carte Mère": "Motherboard",
    "Logique": "Logic",
    "et je suis fier d'être membre actif du club de ping-pong": "and I am proud to be an active member of the ping-pong club",
    "(non communiqué)": "(not communicated)",
    "Non défini": "Undefined",
    "Montage PC": "PC mounting",
    "HTML5": "HTML5",
    "Thomas Mayoraz • Portfolio personnel": "Thomas Mayoraz • Personal portfolio",
    "Client Montage PC": "PC Mount Client",
    "Office 365": "Office365",
    "Kingston 32GB DDR5 6000MT/s CL30": "Kingston 32GB DDR5 6000MT/s CL30",
    "Discutons de votre projet": "Let's discuss your project",
    "Windows 11": "Windows 11",
    "Scripting & Développement Web": "Scripting & Web Development",
    "Thierry Savoy": "Thierry Savoy",
    "079 894 93 43": "079 894 93 43",
    "078 676 70 99": "078 676 70 99",
    "Configuration PC sur mesure": "Custom PC configuration",
    "TM": "TM",
    "Autres Projets": "Other Projects",
    "IoT & Messagerie": "IoT & Messaging",
    "Juin 2026": "June 2026",
    "Cabinet Dentaire Tivoli": "Tivoli Dental Office",
    "Autre (précisez dans le message)": "Other (specify in message)",
    "Thomas Mayoraz • Portfolio professionnel": "Thomas Mayoraz • Professional portfolio",
    ", un projet scolaire qui me permet de mettre en pratique mes compétences en développement web, en particulier pour la création d'un site web statique utilisant uniquement les langages": ", a school project that allows me to practice my web development skills, in particular for the creation of a static website using only the languages",
    "Base de données": "Database",
    "TERMINÉ": "DONE",
    "078 885 94 12": "078 885 94 12",
    "Thomas Mayoraz • Portfolio - Sites Web": "Thomas Mayoraz • Portfolio - Websites",
    "-- Sélectionner --": "-- Select --",
    "Découvrez mes configurations PC personnalisées, assemblées avec soin pour différents usages : gaming, workstation et home server. Chaque build est optimisé pour son usage spécifique.": "Discover my personalized PC configurations, carefully assembled for different uses: gaming, workstation and home server. Each build is optimized for its specific use.",
    "500 - 1000 CHF": "500 - 1000 CHF",
    "90%": "90%",
    "Février 2026": "February 2026",
    "Outlook": "Outlook",
    "Type de demande :": "Type of request:",
    "Les entraînements pour adultes se déroulent les mardis de 19h00 à 22h00": "Adult training takes place on Tuesdays from 7:00 p.m. to 10:00 p.m.",
    "Envoyer le message": "Send message",
    "De la création de sites web au montage PC, en passant par le dépannage informatique, je suis à votre disposition pour concrétiser vos projets technologiques.": "From website creation to PC assembly, including computer troubleshooting, I am at your disposal to bring your technological projects to fruition.",
    "La salle se trouve au collège de la Croix-d'Ouchy": "The room is located at the Croix-d'Ouchy college",
    "Adultes": "Adults",
    "Mes créations digitales et expériences web": "My digital creations and web experiences",
    "Jouer →": "Play →",
    "La salle de sport est ouverte la semaine en dehors des vacances scolaires": "The gym is open during the week outside school holidays",
    "Je vous remercie sincèrement pour votre visite sur mon site ! J'espère que vous apprécierez votre expérience et que vous trouverez les informations utiles. N'hésitez pas à me contacter par mail avec le petit boutton se trouvant en bas de page.": "I sincerely thank you for your visit to my site! I hope you enjoy your experience and find the information useful. Do not hesitate to contact me by email using the little button at the bottom of the page.",
    "Prêt à collaborer ?": "Ready to collaborate?",
    "Gigabyte B650E AORUS Elite X AX ICE": "Gigabyte B650E AORUS Elite",
    "IoT": "IoT",
    "À Propos - Thomas Mayoraz | Services Informatiques Lausanne": "About - Thomas Mayoraz | IT Services Lausanne",
    "Avril 2025": "April 2025",
    "projet du module 293": "module 293 project",
    "Téléphone": "Telephone",
    "Moosmann, Christophe": "Moosmann, Christophe",
    "Le classement se réinitialise tous les jours à minuit.": "The leaderboard resets every day at midnight.",
    "Présentation": "Presentation",
    "Portfolio Personnel": "Personal Portfolio",
    "Mes Services Informatiques dans la région de Lausanne": "My IT Services in the Lausanne region",
    "\"Intervention rapide et très professionnelle. Thomas a réussi à récupérer toutes mes données sur mon disque dur endommagé et m'a conseillé un super système de sauvegarde.\"": "\"Quick and very professional intervention. Thomas managed to recover all my data on my damaged hard drive and recommended a great backup system.\"",
    "★★★★★": "★★★★★",
    "Testez vos connaissances avec un quiz ludique sur l'informatique — rapide, instructif et parfait pour tous les niveaux !": "Test your knowledge with a fun computer science quiz — quick, informative and perfect for all levels!",
    "Me Contacter": "Contact me",
    "AMD Ryzen 7 7700X": "AMD Ryzen 7 7700X",
    "Site web personnel": "Personal website",
    "Les équipes du club": "Club teams",
    "Script PowerShell avancé permettant la collecte de données système sur plusieurs machines via le remoting. Fonctionnalités incluant la génération de rapports, l'export en CSV et la détection d'anomalies. Documentation complète incluse.": "Advanced PowerShell script enabling collection of system data across multiple machines via remoting. Features including report generation, CSV export and anomaly detection. Full documentation included.",
    "Formation": "Training",
    "Sortez à l'arrêt Délices": "Get out at the Délices stop",
    "Rapports": "Reports",
    "Configuration sur mesure selon vos besoins : gaming, bureautique, workstation. Conseil et assemblage.": "Customized configuration according to your needs: gaming, office, workstation. Advice and assembly.",
    "Rapport complet sur la création et configuration de deux machines virtuelles (Windows 11 et Ubuntu) avec VirtualBox. Guide détaillé d'installation, configuration réseau, partage de fichiers et optimisation des performances.": "Complete report on the creation and configuration of two virtual machines (Windows 11 and Ubuntu) with VirtualBox. Detailed installation guide, network configuration, file sharing and performance optimization.",
    "Sur ce site vous trouverez tout ce qu'il faut pour connaître le club, son histoire, ses équipes et sa salle.": "On this site you will find everything you need to know the club, its history, its teams and its room.",
    "Nouveaux projets techniques en préparation...": "New technical projects in preparation...",
    "5ème ligue Hommes Groupe 5, Tours 3&4": "5th League Men Group 5, Rounds 3&4",
    "021 791 41 32": "021 791 41 32",
    "Jeu": "Game",
    "Formulaire de contact - CTT Montriond Ouchy": "Contact form - CTT Montriond Ouchy",
    "Mai 2025": "May 2025",
    "Spécialisé dans les": "Specialized in",
    "Si votre demande est très urgente, n'hésitez pas à m'appeler directement, ou à m'écrire par": "If your request is very urgent, do not hesitate to call me directly, or write to me by",
    "Décembre 2024": "December 2024",
    "Projet d'apprentissage": "Learning project",
    "📊 Télécharger la Présentation": "📊 Download the Presentation",
    "0 - 500 CHF": "0 - 500 CHF",
    "Prochain projet C# en développement...": "Next C# project in development...",
    "Mastermind": "Mastermind",
    "Word": "Word",
    "📄 Télécharger le Rapport": "📄 Download the Report",
    "4ème ligue Hommes Groupe 4, Tours 1&2": "4th League Men Group 4, Rounds 1&2",
    "Il semble que vous soyez perdu dans le cyberespace. La page que vous cherchez a peut-être été supprimée, renommée, ou n'a tout simplement jamais existé.": "It seems you are lost in cyberspace. The page you are looking for may have been deleted, renamed, or simply never existed.",
    "Quiz Tech : Testez Vos Connaissances Informatiques": "Tech Quiz: Test Your Computer Knowledge",
    "MQTT": "MQTT",
    "Découvrez mes projets développés en C#, des applications console aux interfaces graphiques. Chaque projet représente un défi technique relevé et une compétence acquise.": "Discover my projects developed in C#, from console applications to graphical interfaces. Each project represents a technical challenge met and a skill acquired.",
    "Guide Office 365": "Office 365 guide",
    "Prénom :": "First name:",
    "Implémentation complète du jeu Mastermind en C#. Le joueur doit deviner une combinaison secrète de couleurs en un nombre limité d'essais. L'application fournit des indices après chaque tentative et gère différents niveaux de difficulté.": "Complete implementation of the Mastermind game in C#. The player must guess a secret combination of colors in a limited number of tries. The app provides hints after each attempt and manages different difficulty levels.",
    "Perrin, Guy": "Perrin, Guy",
    "Details de l'équipe": "Team details",
    ". L'objectif principal de ce projet est de m'aider à mieux comprendre les bases du développement web tout en mettant en valeur ma créativité et mes compétences techniques dans la réalisation d'un site fonctionnel et esthétique.": ". The main objective of this project is to help me better understand the basics of web development while showcasing my creativity and technical skills in creating a functional and aesthetic site.",
    "Automatisation": "Automation",
    "Prénom": "First name",
    "Site web d'entreprise": "Business website",
    "Console App": "Console App",
    "Seniors III": "Seniors III",
    "Vous trouverez ci-dessous un taleau contenant les différentes équipes du club et un lien permmettant d'accèder aux détails et à leurs résultats récents.": "Below you will find a table containing the different teams of the club and a link allowing access to details and their recent results.",
    ", je propose des solutions sur mesure pour particuliers et entreprises.": ", I offer tailor-made solutions for individuals and businesses.",
    "Systèmes d'Exploitation & Sécurité": "Operating Systems & Security",
    "Gyula Király": "Gyula Király",
    "\"Intervention rapide pour un dépannage sur mon ordinateur de travail qui refusait de démarrer. Réparation efficace et super conseils.\"": "\"Quick intervention for a repair on my work computer which refused to start. Effective repair and great advice.\"",
    "CTT Montriond Ouchy": "CTT Montriond Ouchy",
    "95%": "95%",
    "Ligue Romandie Dames": "Romandie Ladies League",
    "Accès au club": "Access to the club",
    "Bienvenue sur le site web du CTT Montriond-Ouchy": "Welcome to the CTT Montriond-Ouchy website",
    "Lian-Li GALAHAD II 360 Trinity Perf.": "Lian-Li GALAHAD II 360 Trinity Perf.",
    "PowerShell": "PowerShell",
    "Thomas Mayoraz • Portfolio - Builds PC": "Thomas Mayoraz • Portfolio - Builds PC",
    "75%": "75%",
    "2ème ligue Jeunesse Groupe 1": "2nd Youth League Group 1",
    "Configurations personnalisées et optimisées": "Customized and optimized configurations",
    "Excel": "Excel",
    "services informatiques à Lausanne": "IT services in Lausanne",
    "5ème ligue Hommes Groupe 3, Tours 3&4": "5th League Men Group 3, Rounds 3&4",
    "Configuration personnelle": "Personal configuration",
    "Copyright - 2025": "Copyright - 2025",
    "UI/UX": "UI/UX",
    "📦 Télécharger le dossier ZIP": "📦 Download ZIP folder",
    "Mon parcours scolaire à l'ETML m'a permis d'acquérir des bases solides en programmation, administration réseau, gestion de bases de données et montage PC. Mais ce n'est qu'un début : je continue à apprendre chaque jour grâce à mes projets personnels, mes lectures techniques et mes collaborations.": "My school career at ETML allowed me to acquire a solid foundation in programming, network administration, database management and PC assembly. But this is just the beginning: I continue to learn every day through my personal projects, my technical readings and my collaborations.",
    "16 ans": "16 years old",
    "Ville :": "City :",
    "Octobre 2024": "October 2024",
    "📦 Télécharger le Script": "📦 Download the Script",
    "Carte Graphique": "Graphics Card",
    "Les Entraînements": "Training",
    "Assemblages personnalisés et configurations optimisées à Lausanne. Du choix des composants à la mise en service, explorez mes réalisations hardware.": "Custom assemblies and optimized configurations in Lausanne. From the choice of components to commissioning, explore my hardware creations.",
    "Mail": "Email",
    "Alimentation": "Food",
    "Découvrez mes projets de développement web, des sites vitrines aux applications interactives. Chaque création reflète ma passion pour le web moderne et l'expérience utilisateur.": "Discover my web development projects, from showcase sites to interactive applications. Each creation reflects my passion for the modern web and user experience.",
    "🛠️ Mes services en détail": "🛠️ My services in detail",
    "mayoraz-net.ch": "mayoraz-net.ch",
    "🔥 Mes différents projets": "🔥 My different projects",
    "Algorithmique": "Algorithmic",
    "Qui suis-je?": "Who am I?",
    "Projet MQTT sur VM": "MQTT project on VM",
    "Plateforme de gestion": "Management platform",
    "3ème ligue Seniors Groupe 2": "3rd Senior League Group 2",
    "Adresse e-mail :": "E-mail address :",
    "🖥️": "🖥️",
    "Chargement des questions...": "Loading questions...",
    "En parallèle, je poursuis mes études en informatique à l'": "At the same time, I am continuing my studies in computer science at",
    "Autre": "Other",
    "Maxime D.": "Maxime D.",
    "Accès": "Access",
    "4ème ligue Hommes Groupe 5, Tours 1&2": "4th League Men Group 5, Rounds 1&2",
    "Site web que j'ai développé pour mon club de ping-pong, le CTT Montriond Ouchy. Interface moderne et responsive présentant les actualités du club, les équipes, les résultats des matchs et les informations pratiques pour les membres et nouveaux joueurs.": "Website that I developed for my ping-pong club, CTT Montriond Ouchy. Modern and responsive interface presenting club news, teams, match results and practical information for members and new players.",
    "Guide VirtualBox": "VirtualBox Guide",
    "Virtualisation Win11 & Ubuntu": "Win11 & Ubuntu virtualization",
    "📄 Rapport Technique": "📄 Technical Report",
    "Thaler, Yohan": "Thaler, Yohan",
    "VirtualBox": "VirtualBox",
    "Hommes III": "Men III",
    "Turnstile": "Turnstile",
    "Réclamation": "Claim",
    "Thinh Vi Nguyen": "Thinh Vi Nguyen",
    "Parlons de votre projet": "Let's talk about your project",
    "Client Dépannage": "Customer Troubleshooting",
    "Hommes V": "Men V",
    "1 To NVMe SSD + 128 Go SSD": "1TB NVMe SSD + 128GB SSD",
    "E-mail": "Email",
    "6x Lian-Li UNI FAN SL-INF 120 ARGB": "6x Lian-Li UNI FAN SL-INF 120 ARGB",
    "Bonjour ! Je m'appelle": "Good morning ! My name is",
    "Ventilation": "Ventilation",
    "Dames": "Ladies",
    "Des trophées sont à gagner dans les différents tournois": "Trophies are to be won in the different tournaments",
    "Guide": "Guide",
    "Király, Gyula": "Király, Gyula",
    "Documentation": "Documentation",
    "2000 - 5000 CHF": "2000 - 5000 CHF",
    "Réseau": "Network",
    "⚡ Demande urgente ?": "⚡ Urgent request?",
    "Ligue": "League",
    "Contactez-moi dès maintenant pour discuter de votre projet informatique, que ce soit un site web, un montage PC ou une assistance technique.": "Contact me now to discuss your IT project, whether it is a website, PC assembly or technical assistance.",
    "Dépannage informatique": "Computer troubleshooting",
    "Fonction": "Function",
    ", une école technique réputée, où j'approfondis mes connaissances dans le domaine du développement et de la programmation. Ce site web a été conçu dans le cadre de mon": ", a renowned technical school, where I deepen my knowledge in the field of development and programming. This website was designed as part of my",
    "Hardware, Montage PC & Dépannage": "Hardware, PC Assembly & Troubleshooting",
    "Le Club de Tennis de Table de Montriond-Ouchy (CTT Montriond-Ouchy) a été fondé en 1969 et est situé à Lausanne, dans le quartier de la Croix d'Ouchy. Le club compte aujourd'hui plus de 60 membres actifs, âgés de 7 à 77 ans. IlÀ propose des entraînements pour les jeunes le mercredi de 17h30 à 19h, et pour les adultes le mardi de 19h à 22h. La salle est fermée pendant les vacances scolaires. Le club se distingue par son ambiance conviviale, offrant à la fois des séances d'entraînement, du jeu libre et des compétitions.": "The Montriond-Ouchy Table Tennis Club (CTT Montriond-Ouchy) was founded in 1969 and is located in Lausanne, in the Croix d'Ouchy district. The club now has more than 60 active members, aged 7 to 77. IlÀ offers training for young people on Wednesdays from 5:30 p.m. to 7 p.m., and for adults on Tuesdays from 7 p.m. to 10 p.m. The room is closed during school holidays. The club stands out for its friendly atmosphere, offering training sessions, free play and competitions.",
    "Allez ensuite en direction du collège de la croix d'Ouchy et vous serez arrivé sur place.": "Then go towards the Collège de la Croix d'Ouchy and you will have arrived there.",
    "WhatsApp": "WhatsApp",
    "ou": "Or",
    "Vous trouverez ci-dessous le chemin pour accèder au club depuis la gare de lausanne.": "Below you will find the path to access the club from Lausanne train station.",
    "Jeu de Puissance 4 classique développé en C# pour la console. Deux joueurs s'affrontent pour aligner 4 jetons de leur couleur horizontalement, verticalement ou en diagonale. Le jeu inclut une grille interactive, la détection des victoires et la gestion des tours.": "Classic Power 4 game developed in C# for the console. Two players compete to align 4 tokens of their color horizontally, vertically or diagonally. The game includes an interactive grid, win detection and turn management.",
    "+41 76 612 20 53": "+41 76 612 20 53",
    "Les entraînements jeunesse se déroulent le mercredi de 17h30 à 19h00": "Youth training takes place on Wednesdays from 5:30 p.m. to 7:00 p.m.",
    "Budget approximatif (CHF)": "Approximate budget (CHF)",
    "Retour au Portfolio": "Return to Portfolio",
    "À Propos du site": "About the site",
    "Julien P.": "Julien P.",
    "💡 Navigation": "💡 Navigation",
    "[email protected]": "[email protected]",
    "Processeur": "Processor",
    "Conseil technique": "Technical advice",
    "Stockage": "Storage",
    "Adresse :": "Address:",
    "Votre demande a bien été envoyée et je vous en remercie.": "Your request has been sent and I thank you.",
    "Pour revenir à cette page depuis un site, rendez-vous en pied de page d'accueil de chaque site et cliquez sur le bouton de retour au portfolio.": "To return to this page from a site, go to the footer of the home page of each site and click on the return to portfolio button.",
    "Message :": "Message:",
    "Nom": "Name",
    "CSS3": "CSS3",
    "ETML": "ETML",
    "au numéro suivant :": "to the following number:",
    "Projets Divers": "Miscellaneous Projects",
    "L'histoire du club": "The history of the club",
    "Découvrez mon parcours, mes compétences et ma passion pour l'informatique. Expert en services informatiques basé à Lausanne, spécialisé dans les solutions techniques.": "Discover my background, my skills and my passion for IT. Expert in IT services based in Lausanne, specializing in technical solutions.",
    "Trésorier": "Treasurer",
    "🚀 Besoin d'un service ou d'un devis informatique ?": "🚀 Need an IT service or quote?",
    "🛠️": "🛠️",
    "Sites Web": "Websites",
    "Prochain projet en cours...": "Next project in progress...",
    "Hommes II": "Men II",
    "Refroidissement": "Cooling",
    "Que ce soit pour un site web, un montage PC ou un dépannage informatique, je suis là pour vous accompagner. Remplissez le formulaire ci-dessous et je vous répondrai dans les plus brefs délais.": "Whether for a website, PC assembly or computer troubleshooting, I am here to support you. Fill out the form below and I will respond to you as soon as possible.",
    "078 216 87 62": "078 216 87 62",
    "6ème ligue Hommes Groupe 3, Tours 3&4": "6th League Men Group 3, Rounds 3&4",
    "📍 Lausanne, Vaud • Apprenti Informatique ETML": "📍 Lausanne, Vaud • ETML IT Apprentice",
    "Rendez-vous sur la page de contact pour vous inscrire à nos entraînements": "Visit the contact page to sign up for our training",
    "et": "and",
    "SMS": "SMS",
    "Projets C#": "C# projects",
    "Patrick Henri Losey": "Patrick Henri Losey",
    "Responsive": "Responsive",
    "Hyte Y60": "Hyte Y60",
    "Implémentation d'un système de messagerie MQTT entre plusieurs machines virtuelles. Rapport détaillant l'installation de Mosquitto MQTT, la configuration des brokers/clients, la sécurité et des cas d'utilisation pratiques avec exemples de code.": "Implementation of an MQTT messaging system between several virtual machines. Report detailing Mosquitto MQTT installation, broker/client configuration, security and practical use cases with code examples.",
    "☀️": "☀️",
    "AMD Radeon RX 6750 XT": "AMD Radeon RX 6750 XT",
    "Club de Tennis de table de": "Table Tennis Club",
    "Message détaillé": "Detailed message",
    "2ème ligue Hommes Groupe 2, Tours 1&2": "2nd League Men Group 2, Rounds 1&2",
    "Mes Builds PC": "My PC Builds",
    "Projets variés incluant des rapports techniques, des guides pratiques, des documentations et autres créations. Une collection de travaux diversifiés et de ressources utiles.": "Various projects including technical reports, practical guides, documentation and other creations. A collection of diverse works and useful resources.",
    "Conseil Technique": "Technical Advice",
    "EN": "EN",
    "Demande d'information": "Request for information",
    "Entraîneur des jeunes": "Youth coach",
    "Mon propre site web vitrine et portfolio professionnel. Conçu de A à Z pour présenter mes services informatiques, mes réalisations et faciliter la prise de contact grâce à un design moderne, réactif et optimisé.": "My own showcase website and professional portfolio. Designed from A to Z to present my IT services, my achievements and facilitate contact thanks to a modern, responsive and optimized design.",
    "Le club se trouve à Lausanne en Suisse": "The club is located in Lausanne, Switzerland.",
    "3ème ligue Seniors Groupe 3": "3rd Senior League Group 3",
    "Equipes": "Teams",
    "Enermax Revo. DF2 850W 80+ Gold": "Enermax Revo. DF2 850W 80+ Gold",
    "Numéro :": "Number :",
    "Puissance 4": "Power 4",
    "Merci pour votre message !": "Thank you for your message!",
    "Développement d'une solution logicielle complète pour un cabinet dentaire. Réalisation d'une plateforme de gestion des patients et création d'un modèle de facturation automatisé sur mesure pour optimiser l'administration du cabinet.": "Development of a complete software solution for a dental practice. Creation of a patient management platform and creation of a tailor-made automated billing model to optimize practice administration.",
    "À propos du site": "About the site",
    "Bonjour ! Je m'appelle Thomas Mayoraz, j'ai 17 ans et je suis actuellement en 2ème année d'apprentissage informaticien (voie Infra avec Maturité) à l'ETML à Lausanne. Passionné par l'informatique depuis tout petit, j'ai décidé de faire de cette passion un métier.": "Good morning ! My name is Thomas Mayoraz, I am 17 years old and I am currently in the 2nd year of an IT apprenticeship (Infra with Maturity track) at ETML in Lausanne. Passionate about IT since I was little, I decided to turn this passion into a career.",
    "Mon GitHub": "My GitHub",
    "Wolfgang Klose": "Wolfgang Klose",
    "1ère ligue Seniors Groupe 1": "1st Senior League Group 1",
    "Question 1/15": "Question 1/15",
    "Ikwanga, Cosette": "Ikwanga, Cosette",
    "Responsable jeunesse": "Youth manager",
    "Thierry Crelier": "Thierry Crelier",
    "Hommes": "Men",
    "3ème ligue Hommes Groupe 3, Tours 3&4": "3rd League Men Group 3, Rounds 3&4",
    "Développement web professionnel à Lausanne. Sites responsives, applications web modernes et solutions digitales sur mesure pour votre entreprise.": "Professional web development in Lausanne. Responsive sites, modern web applications and tailor-made digital solutions for your business.",
    "Thomas Mayoraz - Services Informatiques Lausanne | Développement Web & Montage PC": "Thomas Mayoraz - IT Services Lausanne | Web Development & PC Editing",
    "Inscription": "Registration",
    "👨‍💻": "👨‍💻",
    "Chemin à emprunter :": "Path to take:",
    "Email": "Email",
    "Virtualisation": "Virtualization",
    ", un club dynamique où je pratique ce sport passionnant avec des personnes incroyables. Depuis que j'ai commencé à jouer, le ping-pong est devenu une véritable passion pour moi, et faire partie de ce club m'apporte de nombreuses opportunités d'amélioration et de convivialité au sein d'une communauté soudée.": ", a dynamic club where I practice this exciting sport with incredible people. Since I started playing, ping pong has become a real passion for me, and being part of this club brings me many opportunities for improvement and conviviality within a close-knit community.",
    "contact@mayoraz-net.ch": "contact@mayoraz-net.ch",
    "Applications console et projets académiques développés en C#. Découvrez mes solutions aux défis de programmation et mes créations personnelles.": "Console applications and academic projects developed in C#. Discover my solutions to programming challenges and my personal creations.",
    "6ème ligue Hommes Groupe 3, Tours 1&2": "6th League Men Group 3, Rounds 1&2",
    "Sophie L.": "Sophie L.",
    "Thomas Mayoraz • Portfolio - Projets C#": "Thomas Mayoraz • Portfolio - C# Projects",
    "Découvrir →": "Discover →",
    "Hommes IV": "Men IV",
    "Ubuntu": "Ubuntu",
    "Script PowerShell de Collecte": "PowerShell Collection Script",
    "Mes développements et applications en C#": "My developments and applications in C#",
    "Contacts du club": "Club Contacts",
    "← Retour au Portfolio": "← Return to Portfolio",
    "Entraînements": "Workouts",
    "Boîtier": "Housing",
    "Résolution de problèmes informatiques, installation de logiciels, optimisation des performances.": "Solving computer problems, installing software, optimizing performance.",
    "Nom :": "Name:",
    "Vous pouvez également m'écrire directement par email :": "You can also write to me directly by email:",
    "Plus de 5000 CHF": "More than 5000 CHF",
    "Yves Rousseau": "Yves Rousseau",
    "CSS": "CSS",
    "Rue :": "Street:",
    "Téléphone :": "Telephone:",
    "ACTIF": "ACTIVE",
    "Présentation PowerPoint complète guidant pas à pas l'installation et la configuration de VirtualBox. Contenu visuel avec captures d'écran, astuces d'optimisation et bonnes pratiques. Parfait pour former des débutants à la virtualisation.": "Complete PowerPoint presentation guiding step-by-step installation and configuration of VirtualBox. Visual content with screenshots, optimization tips and best practices. Perfect for training beginners in virtualization.",
    "3ème ligue Hommes Groupe 3, Tours 1&2": "3rd League Men Group 3, Rounds 1&2",
    "Sélectionnez un service": "Select a service",
    "← Retourner au site principal": "← Return to main site",
    "JavaScript": "JavaScript",
    "Client Récupération de Données": "Customer Data Recovery",
    "À Propos de moi": "About me",
    "Apprenti informaticien passionné": "Passionate IT apprentice",
    "Dépannage": "Troubleshooting",
    "Collecte de données": "Data collection",
    "\"Travail très professionnel ! Thomas a monté mon PC gaming avec un câblage impeccable. Tout tourne à merveille, je recommande vivement.\"": "\"Very professional work! Thomas set up my gaming PC with impeccable cabling. Everything works perfectly, I highly recommend.\"",
    "Virtualisation, Scripts & Guides Techniques": "Virtualization, Scripts & Technical Guides",
    "Thomas Mayoraz": "Thomas Mayoraz",
    "Équipe": "Team",
    ", j'ai": ", I have",
    "Président": "President",
    "Avez-vous essayé de l'éteindre et de la rallumer ? 🔌": "Have you tried turning it off and on again? 🔌",
    "85%": "85%",
    "Depuis la gare de lausanne dirigez-vous vers le metro M2 direction Ouchy olympique.": "From Lausanne station, head towards the M2 metro towards Ouchy Olympic.",
    "1ère ligue Hommes Groupe 1, Tours 3&4": "1st League Men Group 1, Rounds 3&4",
    "Création de sites personnels, portfolios, sites vitrines pour entreprises. Design moderne et responsive.": "Creation of personal sites, portfolios, showcase sites for businesses. Modern and responsive design.",
    "C#": "C#",
    "Mémoire Vive": "RAM",
    "HTML": "HTML",
    "1000 - 2000 CHF": "1000 - 2000 CHF",
    "Ce que disent mes clients": "What my customers say",
    "Date de naissance :": "Date of birth:",
    "la ville du club": "the club city",
    "À propos de moi": "About me",
    "Chloé Werner": "Chloe Werner",
    "Projet de Virtualisation": "Virtualization Project",
    "Administration Réseau & Serveurs": "Network & Server Administration",
    "Accompagnement dans vos choix technologiques, recommandations matériel et logiciel.": "Support in your technological choices, hardware and software recommendations.",
    "Prêt pour le défi ?": "Ready for the challenge?",
    "Je vous répondrai sous 24 heures.": "I will respond to you within 24 hours.",
    "la salle": "the room",
    "Services Informatiques Professionnels": "Professional IT Services",
    "Thomas Mayoraz • Services Informatiques Lausanne • Portfolio professionnel": "Thomas Mayoraz • IT Services Lausanne • Professional portfolio",
    "Quiz sur l'informatique": "Computer science quiz",
    "Capitaine": "Captain",
    "Découvrez mes projets techniques incluant des rapports de virtualisation, scripts PowerShell, implémentations MQTT et guides détaillés. Chaque projet est documenté avec soin et disponible en téléchargement.": "Discover my technical projects including virtualization reports, PowerShell scripts, MQTT implementations and detailed guides. Each project is carefully documented and available for download.",
    "Juin 2025": "June 2025",
    "\"À votre disposition pour tous vos besoins informatiques\"": "“At your disposal for all your IT needs”",
    "Chef technique": "Technical manager",
    "💬 Me Contacter Maintenant": "💬 Contact Me Now",
    "NPA :": "Postcode:",
    "les trophées": "the trophies",
    "🏆 Classement du Jour": "🏆 Ranking of the Day",
    "La jeunesse": "Youth"
,
    "Tutoriels": "Tutorials",
    "Homelab & Serveur": "Homelab & Server",
    "Admin Run": "Admin Run",
    "Base de Connaissances & Guides": "Knowledge Base & Guides",
    "Découvrez mes tutoriels, configurations et astuces d'administration système.": "Discover my tutorials, configurations, and system administration tips.",
    "Déploiement avec Docker Compose": "Deployment with Docker Compose",
    "Comment structurer vos conteneurs et réseaux avec Docker Compose pour une gestion simplifiée.": "How to structure your containers and networks with Docker Compose for simplified management.",
    "L'Auto-Healing avec n8n": "Auto-Healing with n8n",
    "Création de workflows n8n pour redémarrer automatiquement les services Docker qui plantent.": "Creating n8n workflows to automatically restart crashed Docker services.",
    "La Stack \"Arr\" (Jellyfin, Radarr...)": "The 'Arr' Stack (Jellyfin, Radarr...)",
    "Automatisation complète du téléchargement à la lecture en streaming avec le combo magique.": "Complete automation from downloading to streaming playback with the magic combo.",
    "Monitoring avec Prometheus & Grafana": "Monitoring with Prometheus & Grafana",
    "Mise en place de dashboards professionnels pour surveiller la santé de vos serveurs en temps réel.": "Setting up professional dashboards to monitor server health in real-time.",
    "VPN Sécurisé avec Tailscale": "Secure VPN with Tailscale",
    "Comment créer un réseau privé virtuel Mesh (WireGuard) sans ouvrir de ports sur votre box internet.": "How to create a Mesh Virtual Private Network (WireGuard) without opening ports on your router.",
    "Mon Infrastructure": "My Infrastructure",
    "Découvrez l'architecture technique de mon serveur personnel et les services auto-hébergés.": "Discover the technical architecture of my personal server and self-hosted services.",
    "Le Matériel": "Hardware",
    "Une machine virtuelle Ubuntu Server robuste, optimisée pour faire tourner des dizaines de conteneurs Docker sans transpirer.": "A robust Ubuntu Server virtual machine, optimized to run dozens of Docker containers without breaking a sweat.",
    "L'Usine à Médias": "Media Factory",
    "La stack 'Arr' (Radarr, Sonarr, Prowlarr) reliée à qBittorrent et exposée magnifiquement via Jellyfin pour le streaming.": "The 'Arr' stack (Radarr, Sonarr, Prowlarr) linked to qBittorrent and beautifully exposed via Jellyfin for streaming.",
    "Le Monitoring": "Monitoring",
    "Une surveillance constante grâce à Prometheus, qui remonte les métriques système vers des dashboards Grafana stylisés, sans oublier Netdata.": "Constant monitoring thanks to Prometheus, which sends system metrics to stylized Grafana dashboards, not forgetting Netdata.",
    "L'Auto-Réparation (n8n)": "Self-Healing (n8n)",
    "L'automatisation poussée à l'extrême : un workflow n8n qui surveille les conteneurs qui tombent en erreur et les relance de manière autonome.": "Automation pushed to the extreme: an n8n workflow that monitors containers failing and restarts them autonomously.",
    "Admin Run (T-Rex)": "Admin Run (T-Rex)",
    "Appuyez sur ESPACE pour faire sauter l'Administrateur Système au-dessus des bugs !": "Press SPACE to make the System Administrator jump over the bugs!",
    "Score :": "Score :",
    "Meilleur :": "Best :",
    "GAME OVER": "GAME OVER",
    "Appuyez sur Espace pour redémarrer": "Press Space to restart",
    "Statut des Services": "Service Status",
    "Network Status": "Network Status",
    "Systèmes 100% Opérationnels": "Systems 100% Operational",
    "Routeur Principal": "Main Router",
    "Pi-hole (DNS)": "Pi-hole (DNS)",
    "Reverse Proxy Nginx": "Nginx Reverse Proxy",
    "VPN Tailscale": "Tailscale VPN",
    "Cloudflare WAF": "Cloudflare WAF",
    "Serveur Ubuntu (VM)": "Ubuntu Server (VM)",
    "Moteur Docker": "Docker Engine",
    "Jellyfin Media Server": "Jellyfin Media Server",
    "Stack Arr (Sonarr, Radarr...)": "Arr Stack (Sonarr, Radarr...)",
    "Base de Données InfluxDB": "InfluxDB Database",
    "Grafana Dashboards": "Grafana Dashboards",
    "Prometheus Metrics": "Prometheus Metrics",
    "Netdata Live": "Netdata Live",
    "n8n Automation": "n8n Automation",
    "Opérationnel": "Operational",
    "🟢 System Status": "🟢 System Status",
    "Mon LinkedIn": "My LinkedIn",
    "Une question, un projet ou besoin d'assistance ? N'hésitez pas à me contacter via le formulaire dédié. Je vous répondrai très rapidement.": "A question, a project or need assistance? Do not hesitate to contact me via the dedicated form. I will answer you very quickly.",
    "Contacter →": "Contact →",
    "Me Contacter": "Contact Me"
,
    "Intervention rapide et très professionnelle. Thomas a réussi à récupérer toutes mes données sur mon disque dur endommagé et m'a conseillé un super système de sauvegarde.": "Fast and very professional intervention. Thomas managed to recover all my data on my damaged hard drive and advised me on a great backup system.",
    "Intervention rapide pour un dépannage sur mon ordinateur de travail qui refusait de démarrer. Réparation efficace et super conseils.": "Quick intervention for troubleshooting my work computer that refused to start. Efficient repair and great advice.",
    "Travail très professionnel ! Thomas a monté mon PC gaming avec un câblage impeccable. Tout tourne à merveille, je recommande vivement.": "Very professional work! Thomas built my gaming PC with flawless cable management. Everything runs perfectly, I highly recommend.",
    "À votre disposition pour tous vos besoins informatiques": "At your disposal for all your IT needs",
    "(Films).": "(Movies).",
    "(Séries) ou": "(Series) or",
    "(outil d'automatisation de workflows). Si Prometheus détecte qu'un conteneur crash ou consomme trop de RAM, n8n est capable de redémarrer automatiquement le service défaillant et de m'envoyer une notification.": "(workflow automation tool). If Prometheus detects that a container crashes or consumes too much RAM, n8n is able to automatically restart the failing service and send me a notification.",
    ", de le transmettre au client": ", to transmit it to the client",
    ", et enfin de l'organiser proprement pour le serveur de streaming": ", and finally to organize it cleanly for the streaming server",
    ", je peux accéder à toute mon infrastructure depuis mon téléphone en 4G, de manière totalement sécurisée et cryptée avec Wireguard sous le capot.": ", I can access my entire infrastructure from my phone on 4G, completely securely and encrypted with Wireguard under the hood.",
    ". En l'installant sur ma VM Ubuntu et en l'activant en tant que": ". By installing it on my Ubuntu VM and activating it as a",
    ". J'ai fait le choix d'isoler chaque service dans des conteneurs": ". I made the choice to isolate each service in containers",
    "Afin de m'assurer que le serveur n'est jamais surchargé, j'utilise": "To ensure the server is never overloaded, I use",
    "Appuyez sur": "Press",
    "Architecture Média Automatisée": "Automated Media Architecture",
    "Architecture de la Stack \"Arr\"": "\"Arr\" Stack Architecture",
    "Au lieu d'ouvrir les ports de mon routeur à internet (et risquer des attaques), j'utilise": "Instead of opening my router ports to the internet (and risking attacks), I use",
    "Auto-Healing": "Auto-Healing",
    "Auto-Healing : Redémarrer un conteneur crashé": "Auto-Healing : Restart a crashed container",
    "Cloudflare Tunnels": "Cloudflare Tunnels",
    "Dernière vérification: Il y a quelques secondes": "Last check: A few seconds ago",
    "Docker": "Docker",
    "Docker Compose": "Docker Compose",
    "Docker Engine": "Docker Engine",
    "Détails Techniques": "Technical Details",
    "En tant que passionné par l'administration système et réseau, j'héberge et je maintiens ma propre infrastructure à domicile. Ce": "As a system and network administration enthusiast, I host and maintain my own home infrastructure. This",
    "Espace": "Space",
    "Essayez cette commande dans votre terminal :": "Try this command in your terminal:",
    "Gateway Principale": "Main Gateway",
    "Grafana": "Grafana",
    "Grâce à": "Thanks to",
    "Homelab": "Homelab",
    "Infrastructure Personnelle & Automatisation": "Personal Infrastructure & Automation",
    "J'ai déployé la fameuse stack \"Arr\". Les requêtes sont faites via": "I deployed the famous \"Arr\" stack. Requests are made via",
    "Jellyfin": "Jellyfin",
    "Jellyseerr": "Jellyseerr",
    "Jellyseerr (Requêtes)": "Jellyseerr (Requests)",
    "Jellyseerr envoie la requête à": "Jellyseerr sends the request to",
    "L'ensemble de mon infrastructure repose sur une machine virtuelle": "My entire infrastructure relies on a virtual machine",
    "L'utilisateur fait une demande sur": "The user makes a request on",
    "La stack d'automatisation multimédia peut être complexe à relier. Voici le sens des flux :": "The multimedia automation stack can be complex to connect. Here is the flow direction:",
    "Lancer le script": "Run script",
    "Le fichier docker-compose parfait pour débuter": "The perfect docker-compose file to start",
    "Le fichier est envoyé à": "The file is sent to",
    "Le serveur a crashé !": "The server has crashed!",
    "Le système m'envoie ensuite un message sur Telegram pour m'avertir de l'incident et de sa résolution automatique.": "The system then sends me a Telegram message to warn me of the incident and its automatic resolution.",
    "Lent": "Slow",
    "Ma petite base de connaissances technique": "My little technical knowledge base",
    "Media": "Media",
    "Mission : Maintenir le serveur en ligne !": "Mission: Keep the server online!",
    "Mon Homelab": "My Homelab",
    "Mon infrastructure personnelle : Serveur Ubuntu, conteneurs Docker, automatisation média et monitoring avec Grafana.": "My personal infrastructure: Ubuntu Server, Docker containers, media automation, and monitoring with Grafana.",
    "Netdata": "Netdata",
    "Netdata Host Metrics": "Netdata Host Metrics",
    "Nginx Proxy Manager": "Nginx Proxy Manager",
    "Normal": "Normal",
    "Pi-hole DNS & AdBlock": "Pi-hole DNS & AdBlock",
    "Pour aller plus loin qu'un simple monitoring, j'utilise": "To go further than simple monitoring, I use",
    "Pour déployer rapidement n'importe quel conteneur en gardant une trace claire des configurations, j'utilise toujours la structure YAML suivante. Elle intègre les logs rotatifs pour éviter de saturer le disque de la VM.": "To quickly deploy any container while keeping a clear trace of configurations, I always use the following YAML structure. It includes log rotation to avoid saturating the VM disk.",
    "Prometheus": "Prometheus",
    "Prowlarr": "Prowlarr",
    "Prêt à courir ?": "Ready to run?",
    "Quiz Informatique": "IT Quiz",
    "Radarr": "Radarr",
    "Radarr/Sonarr": "Radarr/Sonarr",
    "Rapide": "Fast",
    "Reboot Server": "Reboot Server",
    "Record:": "Record:",
    "Score final :": "Final score:",
    "Score:": "Score:",
    "Sonarr": "Sonarr",
    "Sonarr/Radarr interrogent": "Sonarr/Radarr interrogate",
    "Stack \"Arr\" (Radarr, Sonarr...)": "\"Arr\" Stack (Radarr, Sonarr...)",
    "Subnet Router": "Subnet Router",
    "Surveillance en temps réel de l'infrastructure": "Real-time infrastructure monitoring",
    "Sécuriser son accès avec Tailscale": "Secure access with Tailscale",
    "Tailscale": "Tailscale",
    "Tailscale VPN (Subnet Router)": "Tailscale VPN (Subnet Router)",
    "Testez vos connaissances en IT avec ce quiz interactif. Défiez le classement quotidien !": "Test your IT knowledge with this interactive quiz. Challenge the daily leaderboard!",
    "Thomas Mayoraz |": "Thomas Mayoraz |",
    "Tous les systèmes sont opérationnels": "All systems operational",
    "Tout mon environnement tourne de manière optimisée et isolée, me permettant d'explorer les technologies d'entreprise comme la conteneurisation, le monitoring avancé et l'automatisation de processus.": "My whole environment runs in an optimized and isolated way, allowing me to explore enterprise technologies like containerization, advanced monitoring, and process automation.",
    "Tutoriels & Astuces": "Tutorials & Tips",
    "Ubuntu Server": "Ubuntu Server",
    "Ubuntu Server VM (Host)": "Ubuntu Server VM (Host)",
    "Un mini-jeu SysAdmin : évitez les pannes réseau et maintenez le serveur en ligne !": "A SysAdmin mini-game: avoid network outages and keep the server online!",
    "Une fois téléchargé, Radarr renomme et déplace le fichier vers le dossier final.": "Once downloaded, Radarr renames and moves the file to the final folder.",
    "Voici quelques mémos techniques et configurations rapides basés sur mon expérience avec mon infrastructure personnelle.": "Here are some technical memos and quick configurations based on my experience with my personal infrastructure.",
    "Webhooks": "Webhooks",
    "afin de garantir la stabilité, la sécurité et faciliter les mises à jour et les sauvegardes.": "to ensure stability, security, and facilitate updates and backups.",
    "complète le tout pour le monitoring natif de la VM.": "completes everything for native VM monitoring.",
    "curl --unix-socket /var/run/docker.sock -X POST http://localhost/containers/{container_id}/restart": "curl --unix-socket /var/run/docker.sock -X POST http://localhost/containers/{container_id}/restart",
    "curl https://mayoraz-net.ch/api/cv.json": "curl https://mayoraz-net.ch/api/cv.json",
    "est mon laboratoire d'apprentissage continu.": "is my continuous learning laboratory.",
    "et l'API Docker locale, j'ai créé un workflow qui écoute les alertes webhook de Prometheus. Si un conteneur tombe, n8n lance cette commande via SSH ou Socket :": "and the local Docker API, I created a workflow that listens to Prometheus webhook alerts. If a container goes down, n8n runs this command via SSH or Socket:",
    "n8n": "n8n",
    "n8n Automation Engine": "n8n Automation Engine",
    "ou touchez l'écran pour sauter.": "or touch the screen to jump.",
    "pour collecter les métriques matérielles et applicatives, et": "to collect hardware and application metrics, and",
    "pour trouver les sources via les indexers.": "to find sources via indexers."
,
    "<img>": "<img>",
    "Compiler le code automatiquement": "Compile the code automatically",
    "Un type de processeur": "A type of processor",
    "Avec code source librement accessible": "With freely accessible source code",
    "Qu'est-ce qu'un langage de programmation compilé ?": "What is a compiled programming language?",
    "Qu’est-ce qu’un QR code ?": "What is a QR code?",
    "URL signifie Uniform Resource Locator, c'est l'adresse qui permet d'accéder à une ressource sur internet.": "URL stands for Uniform Resource Locator, it is the address which allows access to a resource on the internet.",
    "Mémoire temporaire pour les programmes en cours d'exécution": "Temporary memory for running programs",
    "2FA signifie Double Facteur d'Authentification, une méthode qui ajoute une couche de sécurité supplémentaire.": "2FA stands for Two-Factor Authentication, a method that adds an extra layer of security.",
    "Mesurer le débit Internet": "Measure Internet Speed",
    "Une fonction": "A function",
    "Gérer l'historique des versions du code": "Manage code version history",
    "Hyperloop Text Management Language": "Hyperloop Text Management Language",
    "Nettoyer l'espace disque": "Clean up disk space",
    "Printable Document Format": "Printable Document Format",
    "Contrôler le trafic réseau entrant et sortant": "Control inbound and outbound network traffic",
    "Stocker les fichiers": "Store files",
    "Exécuter plusieurs systèmes d’exploitation sur un même ordinateur": "Run multiple operating systems on the same computer",
    "Exécuter les instructions des programmes": "Execute program instructions",
    "Un site responsive s’adapte automatiquement à la taille de l’écran (PC, mobile, tablette).": "A responsive site automatically adapts to the size of the screen (PC, mobile, tablet).",
    "Un format d'image": "An image format",
    "HyperText Markup Language": "HyperText Markup Language",
    "Une méthode de tri": "A sorting method",
    "Optimiser la connexion internet": "Optimize the internet connection",
    ".zip": ".zip",
    "Gérer l'alimentation de l’ordinateur": "Manage computer power",
    "Firefox": "Firefox",
    "Ouvre un nouveau document": "Open a new document",
    "Google Chrome est le navigateur développé par Google.": "Google Chrome is the browser developed by Google.",
    "Un navigateur": "A browser",
    "L’interface utilisateur d’un site ou logiciel": "The user interface of a site or software",
    "Quel langage est principalement utilisé pour styliser une page web ?": "What language is mainly used to style a web page?",
    "Une interface pour faire communiquer des logiciels": "An interface for communicating software",
    "Un réseau privé virtuel": "A virtual private network",
    "Un type de fichier": "A file type",
    "CSS (Cascading Style Sheets) est utilisé pour la présentation visuelle des pages web.": "CSS (Cascading Style Sheets) is used for the visual presentation of web pages.",
    "La boucle 'for' permet de répéter une action un certain nombre de fois.": "The 'for' loop allows you to repeat an action a certain number of times.",
    "Gratuit uniquement": "Free only",
    "Enregistre le document en cours": "Saves the current document",
    "L'expéditeur utilise un ton urgent ou menaçant": "The sender uses an urgent or threatening tone",
    "Quelle est la fonction principale d'un pare-feu (firewall) ?": "What is the main function of a firewall?",
    "Les SSD n'ont pas de pièces mobiles": "SSDs have no moving parts",
    "La carte graphique (GPU) gère les calculs d’affichage et de rendu visuel.": "The graphics card (GPU) manages display and visual rendering calculations.",
    "Le code qui tourne sur le serveur": "The code that runs on the server",
    "Une base de données": "A database",
    "La carte mère est le composant central qui connecte tous les autres (CPU, RAM, GPU, etc.).": "The motherboard is the central component that connects all the others (CPU, RAM, GPU, etc.).",
    "Que signifie le terme 'open source' ?": "What does the term 'open source' mean?",
    "Portable Document Format": "Portable Document Format",
    "Windows": "Windows",
    "La touche F5 permet de rafraîchir ou recharger la page en cours.": "The F5 key allows you to refresh or reload the current page.",
    "Toutes ces réponses": "All these answers",
    "PHP est largement utilisé pour exécuter des scripts côté serveur sur les sites web.": "PHP is widely used to run server-side scripts on websites.",
    "Un serveur fournit des services (site web, fichiers, mail...) à d'autres ordinateurs appelés clients.": "A server provides services (website, files, email, etc.) to other computers called clients.",
    "Un langage utilisé uniquement pour le web": "A language used only for the web",
    "Stocker et gérer de manière sécurisée vos identifiants": "Securely store and manage your credentials",
    "Double Format d'Authentification": "Dual Format Authentication",
    "Le protéger contre les virus": "Protect it against viruses",
    "Un fichier système sur MacOS": "A system file on MacOS",
    "Edge": "Edge",
    "Empêcher les emails indésirables": "Prevent unwanted emails",
    "Que faire si votre ordinateur est anormalement lent ?": "What to do if your computer is abnormally slow?",
    "Les emails de phishing utilisent souvent ces techniques pour inciter les victimes à agir rapidement sans réfléchir.": "Phishing emails often use these techniques to trick victims into acting quickly without thinking.",
    ".zip est une extension utilisée pour les fichiers compressés.": ".zip is an extension used for compressed files.",
    "Les fichiers de feuilles de style en cascade (CSS) ont l'extension .css.": "Cascading style sheet (CSS) files have the .css extension.",
    "Un bot est un logiciel qui effectue automatiquement des tâches répétitives sur Internet.": "A bot is software that automatically performs repetitive tasks on the Internet.",
    "Photoshop": "Photoshop",
    "Le processeur": "The processor",
    "Quelle est la différence entre un disque SSD et un HDD ?": "What is the difference between an SSD and an HDD?",
    "Que signifie l'abréviation 'SSD' ?": "What does the abbreviation 'SSD' mean?",
    "Qu'est-ce qu'un VPN ?": "What is a VPN?",
    "HyperText Transfer Protocol Secure": "HyperText Transfer Protocol Secure",
    "Accélérer le démarrage de l’ordinateur": "Speed ​​up computer startup",
    "Que signifie l'acronyme 'URL' ?": "What does the acronym 'URL' mean?",
    "Quel langage est interprété côté client dans les navigateurs web ?": "What language is interpreted on the client side in web browsers?",
    "Un VPN (Virtual Private Network) crée une connexion sécurisée et cryptée entre votre appareil et internet.": "A VPN (Virtual Private Network) creates a secure, encrypted connection between your device and the internet.",
    "Le cloud computing permet d’utiliser des services informatiques (stockage, calcul, etc.) en ligne.": "Cloud computing makes it possible to use IT services (storage, calculation, etc.) online.",
    "La compression permet de réduire la taille des fichiers pour gagner de l’espace ou faciliter le transfert.": "Compression helps reduce file size to save space or facilitate transfer.",
    "Un périphérique de stockage portable": "A portable storage device",
    "Software System Data": "Software System Data",
    "Que permet de faire un logiciel de virtualisation comme VirtualBox ?": "What can virtualization software like VirtualBox do?",
    "Qu'est-ce qu'une adresse IP ?": "What is an IP address?",
    "Les SSD sont plus rapides mais plus chers que les HDD": "SSDs are faster but more expensive than HDDs",
    "Ferme le document": "Close the document",
    "Une technique de hacking": "A hacking technique",
    "C’est une vidéo": "It's a video",
    "Microsoft est l'éditeur du système d'exploitation Windows.": "Microsoft is the publisher of the Windows operating system.",
    "Comment s’appelle le système de fichiers utilisé par Windows ?": "What is the file system used by Windows called?",
    "Un code visuel pouvant contenir des données lisibles par un smartphone": "A visual code that can contain data readable by a smartphone",
    "Un virus": "A virus",
    "Un site qui s’adapte à tous les écrans": "A site that adapts to all screens",
    "Un site sécurisé": "A secure site",
    "Actualise la page": "Refresh the page",
    "Un système de fichiers définit la manière dont les données sont organisées et accédées sur un disque.": "A file system defines how data is organized and accessed on a disk.",
    "C’est une image": "It's a picture",
    "Installer des pilotes de périphériques": "Install device drivers",
    "Une API (Application Programming Interface) permet à des logiciels de communiquer entre eux.": "An API (Application Programming Interface) allows software to communicate with each other.",
    "Que fait la combinaison Ctrl + C ?": "What does Ctrl + C do?",
    "Copie le texte sélectionné": "Copy the selected text",
    "Solid State Drive": "Solid State Drive",
    "Un algorithme est une suite d'étapes permettant de résoudre un problème ou effectuer une tâche.": "An algorithm is a series of steps used to solve a problem or perform a task.",
    "Un conteneur pour stocker des données": "A container to store data",
    "Un périphérique externe": "An external device",
    "Remplir automatiquement les formulaires de connexion": "Automatically fill out login forms",
    "Une publicité": "An advertisement",
    "Une sauvegarde sur un CD/DVD": "A backup on a CD/DVD",
    ".html": ".html",
    "PDF signifie Portable Document Format, un format de fichier pour l’échange de documents.": "PDF stands for Portable Document Format, a file format for exchanging documents.",
    "Ctrl + S est le raccourci universel pour enregistrer (Save) le document ou fichier en cours.": "Ctrl + S is the universal shortcut to save the current document or file.",
    "Microsoft": "Microsoft",
    "Quel est l'intérêt de compresser un fichier ?": "What is the point of compressing a file?",
    "Un format de vidéo": "A video format",
    "La carte graphique": "The graphics card",
    "Annule la dernière action": "Undo the last action",
    "Universal Reference Location": "Universal Reference Location",
    "Empêcher les spams": "Prevent spam",
    "Un programme de montage vidéo": "A video editing program",
    "Qu’est-ce qu’un système de fichiers ?": "What is a file system?",
    "Un site avec des animations": "A site with animations",
    "Protéger le disque dur": "Protect the hard drive",
    "PHP": "PHP",
    "Connecter les appareils au réseau et à Internet": "Connect devices to the network and the Internet",
    "Un identifiant matériel unique d’une carte réseau": "A unique hardware identifier of a network card",
    "Double Fichier d'Accès": "Double File Access",
    "Java": "Java",
    "Ouvre le menu contextuel": "Open context menu",
    "Swift": "Swift",
    "Apple": "Apple",
    "Détecter et supprimer les logiciels malveillants": "Detect and remove malware",
    "Que signifie l’acronyme 'PDF' ?": "What does the acronym 'PDF' mean?",
    "Qu'est-ce qu'un fichier PDF ?": "What is a PDF file?",
    "Créer des disques durs plus rapides": "Create faster hard drives",
    "Quel est le rôle du DNS sur Internet ?": "What is the role of DNS on the Internet?",
    "Un programme automatisé pour exécuter des tâches": "An automated program to perform tasks",
    "C++": "C++",
    "Un antivirus": "An antivirus",
    "Un périphérique": "A device",
    "Une variable est un conteneur qui stocke des données qui peuvent être modifiées pendant l'exécution du programme.": "A variable is a container that stores data that can be modified during program execution.",
    "Un QR code est un code visuel qui peut contenir du texte, des liens, etc., lisibles via caméra.": "A QR code is a visual code that can contain text, links, etc., readable via camera.",
    "À quoi sert un fichier '.exe' sous Windows ?": "What is an '.exe' file used for in Windows?",
    "Basic Input Option System": "Basic Input Option System",
    "Analyser un virus": "Scan a virus",
    "Accélérer la connexion internet": "Speed ​​up the internet connection",
    "Quelle est l'extension de fichier d'une feuille de style CSS ?": "What is the file extension of a CSS style sheet?",
    "L’intelligence artificielle permet aux systèmes d’apprendre à partir de données pour accomplir des tâches automatiquement.": "Artificial intelligence allows systems to learn from data to accomplish tasks automatically.",
    "Qu'est-ce qu'une boucle 'for' en programmation ?": "What is a 'for' loop in programming?",
    "HyperText Markdown Language": "HyperText Markdown Language",
    "Une suite bureautique": "An office suite",
    "SSD signifie Solid State Drive, un type de disque rapide et sans pièces mécaniques.": "SSD stands for Solid State Drive, a type of disk that is fast and has no mechanical parts.",
    "Windows utilise principalement le système de fichiers NTFS.": "Windows primarily uses the NTFS file system.",
    "Que fait la combinaison de touches Ctrl + S dans un logiciel ?": "What does the Ctrl + S key combination do in software?",
    "HTTPS est plus rapide": "HTTPS is faster",
    "La RAM": "RAM",
    "Le frontend désigne l’interface visible avec laquelle l’utilisateur interagit.": "The frontend designates the visible interface with which the user interacts.",
    "Ferme le programme": "Close the program",
    "Utiliser un ordinateur sans Internet": "Use a computer without Internet",
    "Quel langage est utilisé pour interagir avec des bases de données relationnelles ?": "What language is used to interact with relational databases?",
    "Une application mobile": "A mobile application",
    "Que permet un câble HDMI ?": "What does an HDMI cable do?",
    "Super Speed Disk": "Super Speed ​​Disk",
    ".css": ".css",
    "Quelle est la différence principale entre HTTP et HTTPS ?": "What is the main difference between HTTP and HTTPS?",
    "Quel système d’exploitation est basé sur le noyau Linux ?": "Which operating system is based on the Linux kernel?",
    "JavaScript est exécuté directement dans le navigateur de l'utilisateur.": "JavaScript is executed directly in the user's browser.",
    "Que signifie l'acronyme 'HTML' ?": "What does the acronym 'HTML' mean?",
    "Le DNS traduit les noms de domaine comme google.com en adresses IP.": "DNS translates domain names like google.com into IP addresses.",
    "Safari": "Safari",
    "HyperText Transfer Protocol System": "HyperText Transfer Protocol System",
    "Améliorer les performances graphiques": "Improve graphics performance",
    "Le BIOS": "The BIOS",
    "Ctrl + C permet de copier une sélection dans le presse-papiers.": "Ctrl + C copies a selection to the clipboard.",
    "EXT4": "EXT4",
    "La commande ping permet de tester si un appareil distant est accessible sur un réseau.": "The ping command allows you to test whether a remote device is accessible on a network.",
    "Universal Resource Locator": "Universal Resource Locator",
    "L’adresse d’un site Apple": "The address of an Apple site",
    "Le disque dur": "The hard drive",
    "Changer son format": "Change its format",
    "Que fait la combinaison Ctrl + Z ?": "What does Ctrl + Z do?",
    "Qu'est-ce qu'un serveur ?": "What is a server?",
    "Protéger contre les logiciels malveillants": "Protect against malware",
    "Qu'est-ce qu'un algorithme ?": "What is an algorithm?",
    "Une erreur ou défaillance dans un programme": "An error or failure in a program",
    "La carte graphique (GPU) est le composant clé pour le rendu et la fluidité dans les jeux vidéo.": "The graphics card (GPU) is the key component for rendering and fluidity in video games.",
    "HighText Machine Language": "HighText Machine Language",
    "Un périphérique audio": "An audio device",
    "Un gestionnaire de mots de passe offre toutes ces fonctionnalités pour une meilleure sécurité en ligne.": "A password manager offers all these features for better online security.",
    "Un cookie est un petit fichier permettant de stocker des informations de navigation utilisateur.": "A cookie is a small file used to store user browsing information.",
    "Qu'est-ce qu'une clé USB ?": "What is a USB key?",
    "VirtualBox permet d'exécuter plusieurs OS simultanément sur la même machine.": "VirtualBox allows you to run several OS simultaneously on the same machine.",
    "Fournir de l'énergie aux composants": "Providing energy to components",
    "Que signifie l'acronyme 'BIOS' ?": "What does the acronym 'BIOS' mean?",
    "La balise <img> permet d'insérer des images dans une page HTML.": "The <img> tag allows you to insert images into an HTML page.",
    "Private Digital File": "Private Digital File",
    "Comment reconnaître un email de phishing ?": "How to recognize a phishing email?",
    "Un type de réseau": "A type of network",
    "Un format de base de données": "A database format",
    "Ouvre une nouvelle fenêtre": "Opens a new window",
    "Transférer uniquement la vidéo": "Transfer video only",
    "Binary Integrated Operating System": "Binary Integrated Operating System",
    "Ferme l'onglet": "Close the tab",
    "HFS+": "HFS+",
    "Ouvre les paramètres": "Open settings",
    "Une structure de répétition": "A repetition structure",
    "Colle du texte": "Paste text",
    "HTML signifie HyperText Markup Language, utilisé pour structurer le contenu des pages web.": "HTML stands for HyperText Markup Language, used to structure the content of web pages.",
    "Public Data File": "Public Data File",
    "Créer des programmes dans le ciel": "Create programs in the sky",
    "Quelle balise HTML est utilisée pour insérer une image ?": "Which HTML tag is used to insert an image?",
    "Qu’est-ce qu’une API ?": "What is an API?",
    "Google": "Google",
    "Visual Studio Code": "Visual Studio Code",
    "Tester la connectivité réseau entre deux machines": "Test network connectivity between two machines",
    "Un outil de tracking": "A tracking tool",
    "Quel navigateur a été développé par Google ?": "Which browser was developed by Google?",
    "Une adresse IP": "An IP address",
    "C’est un fichier exécutable": "This is an executable file",
    "Accélérer le chargement des pages": "Speed ​​up page loading",
    "Que signifie 'bug' en informatique ?": "What does 'bug' mean in computer science?",
    "Un routeur connecte les appareils au réseau local et à Internet.": "A router connects devices to the local network and the Internet.",
    "HyperText Transfer Protocol Service": "HyperText Transfer Protocol Service",
    "Afficher la température du processeur": "Show CPU temperature",
    "Le clavier": "The keyboard",
    "Qu'est-ce qu'un système d'exploitation ?": "What is an operating system?",
    "Git est un système de gestion de versions permettant de suivre les modifications du code source.": "Git is a version management system for tracking changes to source code.",
    "Un pare-feu surveille et contrôle le trafic réseau selon des règles de sécurité définies.": "A firewall monitors and controls network traffic according to defined security rules.",
    "Alimentation électrique des composants": "Power supply of components",
    "Un antivirus protège l'ordinateur contre les virus et logiciels malveillants.": "An antivirus protects the computer against viruses and malware.",
    "Toutes ces solutions peuvent aider à améliorer les performances d'un ordinateur lent.": "All of these solutions can help improve the performance of a slow computer.",
    "Une image contenant du texte": "An image containing text",
    "Une extension de navigateur": "A browser extension",
    "Enregistre le fichier": "Save the file",
    "Que signifie 'HTTPS' dans une URL ?": "What does 'HTTPS' mean in a URL?",
    "HTTP est plus sécurisé": "HTTP is more secure",
    "Un composant matériel": "A hardware component",
    ".txt": ".txt",
    "Un programme ou appareil qui fournit des services à d'autres": "A program or device that provides services to others",
    "Une clé USB permet de stocker et transférer des fichiers facilement.": "A USB key allows you to store and transfer files easily.",
    "Convertir les noms de domaine en adresses IP": "Convert domain names to IP addresses",
    "L'adresse email de l'expéditeur semble inhabituelle": "The sender's email address seems unusual",
    "Avec code source fermé": "With closed source code",
    "NTFS": "NTFS",
    "<src>": "<src>",
    "HTTPS chiffre les échanges de données, contrairement à HTTP.": "HTTPS encrypts data exchanges, unlike HTTP.",
    "Un commentaire dans le programme": "A comment in the program",
    "Afficher les images": "Show images",
    "Vérifier les programmes en cours d'exécution": "Check running programs",
    "Une partie d'un disque dur": "Part of a hard drive",
    "À quoi sert un gestionnaire de mots de passe ?": "What is a password manager for?",
    "Une adresse de messagerie": "An email address",
    "Un langage qui ne peut pas contenir d'erreurs": "A language that cannot contain errors",
    "Uniform Resource Locator": "Uniform Resource Locator",
    "Basic Input Output System": "Basic Input Output System",
    "Les HDD utilisent des plateaux magnétiques, les SSD de la mémoire flash": "HDDs use magnetic platters, SSDs use flash memory",
    "Un numéro de série de carte graphique": "A graphics card serial number",
    "Créer des mots de passe complexes": "Create complex passwords",
    "Un câble HDMI permet de transmettre à la fois de l’audio et de la vidéo en haute définition.": "An HDMI cable allows you to transmit both high definition audio and video.",
    "Afficher les images à l'écran": "View images on screen",
    "Stocker ses données sur une disquette": "Store your data on a floppy disk",
    "Qu’est-ce qu’un cookie sur un site web ?": "What is a cookie on a website?",
    "Que signifie 'responsive' en développement web ?": "What does 'responsive' mean in web development?",
    "Une mise à jour importante": "An important update",
    "Le système d'exploitation (comme Windows, macOS ou Linux) est le logiciel principal qui gère toutes les ressources de l'ordinateur.": "The operating system (like Windows, macOS, or Linux) is the primary software that manages all of the computer's resources.",
    "PDF (Portable Document Format) est utilisé pour présenter des documents de manière fiable, quel que soit le logiciel ou appareil.": "PDF (Portable Document Format) is used to present documents reliably, regardless of software or device.",
    "Un fichier temporaire de configuration": "A temporary configuration file",
    "FAT32": "FAT32",
    "Quel est le rôle de l’IA dans l’informatique moderne ?": "What is the role of AI in modern computing?",
    ".exe": ".exe",
    "Un format de document universel": "A universal document format",
    "Un protocole de messagerie": "A messaging protocol",
    "Bash": "bash",
    "Quel langage est souvent utilisé pour développer des applications Android ?": "What language is often used to develop Android applications?",
    "Qu'est-ce qu'un bot informatique ?": "What is a computer bot?",
    "Remplacer Internet": "Replace Internet",
    "Redémarrer l'ordinateur": "Restart the computer",
    "SQL (Structured Query Language) est utilisé pour interroger et gérer les bases de données relationnelles.": "SQL (Structured Query Language) is used to query and manage relational databases.",
    "Rendre son contenu illisible": "Make your content unreadable",
    "Uniquement pour les professionnels": "Only for professionals",
    "Connecter et faire communiquer tous les composants": "Connect and communicate all components",
    "Unified Resource Link": "Unified Resource Link",
    "Transférer des fichiers entre ordinateurs": "Transfer files between computers",
    "Colle le texte copié": "Paste the copied text",
    "Un type de virus": "A type of virus",
    "Java est l’un des principaux langages utilisés pour le développement Android.": "Java is one of the major languages ​​used for Android development.",
    "Un raccourci clavier": "A keyboard shortcut",
    "Ctrl + Z permet d’annuler la dernière action effectuée.": "Ctrl + Z allows you to undo the last action performed.",
    "Utiliser des ressources informatiques via Internet": "Use computer resources via the Internet",
    "Alimenter l’ordinateur": "Power the computer",
    "Une condition logique": "A logical condition",
    "Une adresse IP identifie de façon unique un appareil sur un réseau.": "An IP address uniquely identifies a device on a network.",
    "Basic Internet Operating System": "Basic Internet Operating System",
    "Qu'est-ce qu'une sauvegarde 'cloud' ?": "What is a 'cloud' backup?",
    "SQL": "SQL",
    "HTTP est utilisé pour les vidéos uniquement": "HTTP is used for videos only",
    "Créer des documents PDF": "Create PDF documents",
    "Un programme pour naviguer sur internet": "A program to browse the internet",
    ".scss": ".scss",
    "L’adresse MAC est un identifiant unique attribué à une interface réseau.": "The MAC address is a unique identifier assigned to a network interface.",
    "Un périphérique réseau": "A network device",
    "Un bug est une erreur dans le code source qui entraîne un comportement inattendu ou incorrect.": "A bug is an error in the source code that causes unexpected or incorrect behavior.",
    "Smart Storage Device": "Smart Storage Device",
    "Une sauvegarde sur un disque externe": "A backup to an external drive",
    "Transférer uniquement l'audio": "Transfer audio only",
    "Un site qui répond vite": "A site that responds quickly",
    "Que permet la commande 'ping' ?": "What does the 'ping' command do?",
    ".jpg": ".jpg",
    "Quelle entreprise développe le système d'exploitation Windows ?": "Which company develops the Windows operating system?",
    "Un langage transformé en langage machine avant l'exécution": "A language transformed into machine language before execution",
    "Sécuriser les connexions": "Secure connections",
    "Le cloud computing permet de stocker des données sur des serveurs distants accessibles via internet.": "Cloud computing allows data to be stored on remote servers accessible via the internet.",
    "Une sauvegarde sur une clé USB": "A backup on a USB key",
    "Que signifie '2FA' en sécurité informatique ?": "What does '2FA' mean in IT security?",
    "Ubuntu est une distribution Linux populaire et gratuite.": "Ubuntu is a popular and free Linux distribution.",
    "Les SSD sont plus rapides, plus durables mais plus chers que les HDD traditionnels.": "SSDs are faster, more durable but more expensive than traditional HDDs.",
    "Qu’est-ce qu’une adresse MAC ?": "What is a MAC address?",
    "Quel composant détermine principalement la fluidité des jeux vidéo ?": "Which component mainly determines the fluidity of video games?",
    "Une sauvegarde sur un serveur distant via internet": "A backup on a remote server via the internet",
    "<pic>": "<pic>",
    "Quel est le rôle principal d’un routeur dans un réseau domestique ?": "What is the main role of a router in a home network?",
    "Un logiciel de traitement de texte": "Word processing software",
    "Quelle extension correspond à un fichier compressé ?": "What extension corresponds to a compressed file?",
    "Un logiciel open source est distribué avec un code source accessible et modifiable.": "Open source software is distributed with accessible and modifiable source code.",
    "Les fichiers '.exe' sont des exécutables qui permettent de lancer des logiciels sur Windows.": "'.exe' files are executables that allow you to launch software on Windows.",
    "Quel est le rôle de la carte mère dans un ordinateur ?": "What is the role of the motherboard in a computer?",
    "Transférer l'audio et la vidéo en haute définition": "Transfer audio and video in high definition",
    "Permettre à des systèmes d’apprendre et s’adapter": "Enable systems to learn and adapt",
    "Réduire sa taille pour un stockage ou un envoi plus facile": "Reduce its size for easier storage or shipping",
    "Un périphérique de stockage": "A storage device",
    "Un mot de passe réseau": "A network password",
    "Chrome": "Chromium",
    "Le matériel informatique": "Computer hardware",
    "Créer des interfaces utilisateur": "Create user interfaces",
    "Stockeur des données": "Data store",
    "Quel est le rôle principal d'un antivirus ?": "What is the main role of an antivirus?",
    "Améliorer la qualité du signal Wi-Fi": "Improve Wi-Fi signal quality",
    "Contrôle de la carte graphique": "Graphics card control",
    "Que fait la touche F5 dans la plupart des navigateurs web ?": "What does the F5 key do in most web browsers?",
    "Double Facteur d'Authentification": "Double Factor Authentication",
    "Double Fréquence d'Accès": "Dual Access Frequency",
    "Python": "Python",
    "Un langage compilé est transformé en code machine par un compilateur avant d'être exécuté.": "A compiled language is transformed into machine code by a compiler before being executed.",
    "Stockage permanent des fichiers": "Permanent file storage",
    "Un langage qui s'exécute directement sans transformation": "A language that executes directly without transformation",
    "BIOS signifie Basic Input Output System, il initialise le matériel à l’allumage.": "BIOS stands for Basic Input Output System, it initializes the hardware when powered on.",
    "Un logiciel qui gère les ressources matérielles et logicielles de l'ordinateur": "Software that manages computer hardware and software resources",
    "HTTPS chiffre les données échangées": "HTTPS encrypts the data exchanged",
    "Que signifie 'cloud computing' ?": "What does 'cloud computing' mean?",
    ".style": ".style",
    "IBM": "IBM",
    "Un identifiant unique pour un appareil sur un réseau": "A unique identifier for a device on a network",
    "Que signifie le terme 'frontend' ?": "What does the term 'frontend' mean?",
    "Un programme": "A program",
    "La RAM (Random Access Memory) est une mémoire volatile utilisée pour stocker temporairement les données des programmes en cours d'exécution.": "RAM (Random Access Memory) is volatile memory used to temporarily store data from running programs.",
    "Une erreur dans le code": "An error in the code",
    "macOS": "macOS",
    "Quel logiciel est utilisé pour écrire du code ?": "What software is used to write code?",
    "HTTPS est la version sécurisée du HTTP, avec un chiffrement des données échangées.": "HTTPS is the secure version of HTTP, with encryption of the data exchanged.",
    "Une façon d’organiser les données sur un support de stockage": "A way to organize data on a storage medium",
    "Créer des sauvegardes": "Create backups",
    "Quel composant est le plus responsable du rendu graphique dans un jeu vidéo ?": "Which component is most responsible for graphics rendering in a video game?",
    "Quelle est la fonction principale d'un processeur (CPU) ?": "What is the main function of a processor (CPU)?",
    "Il contient des liens ou pièces jointes suspects": "It contains suspicious links or attachments",
    "<image>": "<picture>",
    "Un virus informatique": "A computer virus",
    "À quoi sert la RAM dans un ordinateur ?": "What is RAM used for in a computer?",
    "Sauvegarder les fichiers sur le cloud": "Back up files to the cloud",
    "Le CPU (Central Processing Unit) est le cerveau de l'ordinateur qui exécute les instructions des programmes.": "The CPU (Central Processing Unit) is the brain of the computer which executes program instructions.",
    "C’est un fichier texte": "This is a text file",
    "À quoi sert Git dans un projet informatique ?": "What is Git used for in an IT project?",
    "Une série d’instructions pour résoudre un problème": "A series of instructions to solve a problem",
    "Sécuriser les ports USB": "Secure USB ports",
    "HyperText Transfer Protocol Standard": "HyperText Transfer Protocol Standard",
    "Qu'est-ce qu'une variable en programmation ?": "What is a variable in programming?",
    "Ruby": "Ruby",
    "Quel langage est majoritairement utilisé pour les scripts côté serveur web ?": "What language is mostly used for web server-side scripting?",
    "Un langage de programmation": "A programming language",
    "Visual Studio Code est un éditeur de code source populaire pour les développeurs.": "Visual Studio Code is a popular source code editor for developers."
};

const enToFr = {};
for (const [fr, en] of Object.entries(frToEn)) {
    enToFr[en] = fr;
}

let currentLang = localStorage.getItem('site_lang') || 'FR';

function translateTextNode(node, dict) {
    const text = node.nodeValue.trim();
    if (text && dict[text]) {
        node.nodeValue = node.nodeValue.replace(text, dict[text]);
    }
}

function applyLanguage(targetLang) {
    const isToEn = targetLang === 'EN';
    const activeDict = isToEn ? frToEn : enToFr;

    const walk = document.createTreeWalker(
        document.body,
        NodeFilter.SHOW_TEXT,
        null,
        false
    );

    let node;
    const nodesToTranslate = [];
    while ((node = walk.nextNode())) {
        if (node.parentElement && (node.parentElement.tagName === 'SCRIPT' || node.parentElement.tagName === 'STYLE')) {
            continue;
        }
        nodesToTranslate.push(node);
    }

    nodesToTranslate.forEach(n => translateTextNode(n, activeDict));

    const placeholders = document.querySelectorAll('input[placeholder], textarea[placeholder]');
    placeholders.forEach(inp => {
        const text = inp.getAttribute('placeholder');
        if (text && activeDict[text]) {
            inp.setAttribute('placeholder', activeDict[text]);
        }
    });

    const langBtn = document.getElementById('lang-toggle');
    if (langBtn) {
        langBtn.textContent = targetLang === 'EN' ? 'FR' : 'EN';
    }
    
    document.documentElement.lang = targetLang.toLowerCase();
}

document.addEventListener('DOMContentLoaded', () => {
    if (currentLang === 'EN') {
        applyLanguage('EN');
    }

    const langBtn = document.getElementById('lang-toggle');
    if (langBtn) {
        langBtn.addEventListener('click', () => {
            currentLang = currentLang === 'FR' ? 'EN' : 'FR';
            localStorage.setItem('site_lang', currentLang);
            applyLanguage(currentLang);
            
            if (typeof showToast === 'function') {
                showToast(currentLang === 'EN' ? 'Language switched to English 🌍' : 'Langue changée en Français 🌍', 'info');
            }
        });
    }
});

// Helper global pour traduire les chaînes de caractères dans le JS
window.t = function(text) {
    if (typeof currentLang !== 'undefined' && currentLang === 'EN') {
        return frToEn[text] || text;
    }
    return text;
};
